### ISSUE TITLE
iCubShenzhen01 left hand's thumb had a problem again.

### ISSUE THREAD

**Issue by tKsome** [robotology/icub-tech-support#1015]
![276561941](https://user-images.githubusercontent.com/28921533/97156749-1a6e8400-17b2-11eb-817b-edb0aacc2e3b.jpg)
![702840973](https://user-images.githubusercontent.com/28921533/97156756-1cd0de00-17b2-11eb-9389-20aafe9deafb.jpg)

## Brief description of the request/failure
After the repair of the broken cable, the thumb can already be controlled, but there are still cable stuck sounds. And When i want to give the thumb a wide angle, the motor keeps ringing(i think the motor is idling). And sometimes JOINT8 is no longer controlled after the maximum angle.

**Comment by tKsome** [comment]
this problem should be the cable broken last time but we donnot find it. and it also broken in left hand
[1603708127211.zip](https://github.com/robotology/icub-tech-support/files/5438261/1603708127211.zip)

**Comment by violadelbono** [comment]
Hi @tKsome 

From your pictures and video it seems to me that this time the thumb oppose cable broke (joint 8).

This motor is located inside the hand, so you will not need to remove the forearm (luckily!).
Here you can read the documentation related:

https://icub-tech-iit.github.io/documentation/icub_tendons/wrist_hand_cabling_V2/#21-location

I suggest you first ensure that the thumb oppose is the cable that is actually broken and then read the procedure carefully in order to repair it. We can call on Skype in case you need advice.

**Comment by tKsome** [comment]
@violadelbono hi, we need you help, the broken cable cannot come off

**Comment by violadelbono** [comment]
Call me on Skype

**Comment by tKsome** [comment]
We fixed the tendon, but the left arm joint 8's encoder seems to be broken

**Comment by julijenv** [comment]
Hi @tKsome ,
didi you get some good news from the sensor?
let us know
