### ISSUE TITLE
iCubGenova08: Right arm J3 hw fault

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-tech-support#1020]
## Brief description of the request/failure
The elbow of the right arm stops working due to an hardware fault on J3.

## Detailed context
![rightarm_hwfault](https://user-images.githubusercontent.com/3440640/97848729-cbfd4000-1cf1-11eb-8042-77c024151202.jpg)

## Accompanying material
[log_pc104_yarprobotinterface_1579.txt](https://github.com/robotology/icub-tech-support/files/5473727/log_pc104_yarprobotinterface_1579.txt)

**Comment by maggia80** [comment]
@julijenv  @violadelbono  please check here the docs: [iCub 2.7 Logic&Harness](https://icub-tech-iit.github.io/documentation/icub_wiring/icub2_x/#logic-and-harness-icub-27-e36-full-robot-with-high-performance-imu-on-the-waist-and-new-face-expressions)

the faulty encoder should be the one in the picture below:  
![image](https://user-images.githubusercontent.com/6987330/97849947-a2ddaf00-1cf3-11eb-996f-ec4447f2197b.png)

**Comment by julijenv** [comment]
Hi @ddetommaso , As mentionned previously by @maggia80 (thx btw) both the yarpmotorgui and the lof file direct to this problem.
I will try to schedule an intervnetion, I will try to get the car to pass by. Which day for you would be better in the week in order to do not disturb your planning?
let us know, ASAP, when you give me some day I will ask the car and in the same hope to get feedback in order to let you know

**Comment by ddetommaso** [comment]
Hi @julijenv 

thank you for your availability.
In BP a suitable time schedule would be on Friday starting from 11:00. Please contact directly D. Ghiglino  for further information.

**Comment by julijenv** [comment]
Hi there,
the cable ground 
![image](https://user-images.githubusercontent.com/7140395/98384925-adc77500-204e-11eb-9813-3a24901998d6.png)

was barely connected , which was actually creating the fault from time to time depending on th e movement.
recrimping save the issue.
we made almost 70 trials with 0% failure so I close the issue
