### ISSUE TITLE
Right hand middle finger distal joint cable is broken

### ISSUE THREAD

**Issue by kouroshD** [robotology/icub-tech-support#1030]
## Brief description of the request/failure

The  middle finger distal joint cable of the right hand is broken.

## Detailed context

Thanks to @julijenv  fixes last night, I managed to do a test I needed for collecting data to see the relationship between the motor currents and external forces acting on the finger. Unfortunately, I broke the right middle finger distal joint cable in this process (sorry @julijenv :(  ). 

## Accompanying material

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/17707730/99648480-60d29e00-2a53-11eb-9a17-c6360d4ed8fd.png)
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/17707730/99648489-63cd8e80-2a53-11eb-80ca-e91918844cba.png)
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/17707730/99648497-64febb80-2a53-11eb-9d18-1af7b7b7fe75.png)

**Comment by violadelbono** [comment]
Hi @kouroshD 

The finger is fixed.

| IITCODE  |  QUANTITY | DESCRIPTION  |ALIAS   | 
|---|---|---|---|
| 2391  | 50cm  | Stainless steel micro-cable, cable construction 7x19mm, nom. diameter 0.45mm, outer diameter 0.61mm, Polyamide coated, AISI 316 - CARL STAHL GMBH  | U7194561  |   

**PS.** I noticed some problems when launching the robot interface -I recalibrated left arm wrist (j4 j5), fingers abduction (j7) and little fingers (j15) because they were out of range.

Now all the joints start correctly (no HW fault)

**Comment by kouroshD** [comment]
Hi @violadelbono  Thank you a lot for taking care of the broken cable of the finger. Feel free to close the issue.
