### ISSUE TITLE
Weird noises when moving the right knee and the right hip roll

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1077]
## Brief description of the request/failure
With iCub3 there are weird noises when moving the knee via the motorgui. They are audible also at startup. When moving the right hip roll by hand instead, sometimes it produces a metallic noise that seems to be coming from the hip pitch assembly.

We would need to discuss this with @pattacini @salvi-mattia and @maggia80.

cc @DanielePucci @isorrentino @GiulioRomualdi

**Comment by pattacini** [comment]
Thanks @S-Dafarra for reporting 👍🏻 
We will be dealing with this "huge" issue after an internal discussion on how to allocate resources.

**Comment by pattacini** [comment]
After today's meeting, it came out that we would need quite some days of downtime in order to carefully inspect all the parts and at the same time install the battery. Keeping some margins, **one workweek** (probably less) should be sufficient.

Our proposal is to start off this maintenance the **first week of March 01-05/03** (we cannot do that before, unfortunately).
Does it work for you?

**Comment by S-Dafarra** [comment]
> After today's meeting, it came out that we would need quite some days of downtime in order to carefully inspect all the parts and at the same time install the battery. Keeping some margins, **one workweek** (probably less) should be sufficient.
> 
> Our proposal is to start off this maintenance the **first week of March 01-05/03** (we cannot do that before, unfortunately).
> Does it work for you?

Thanks @pattacini, I think it should be ok. In any case, let me ping other people involved with the experiments to make sure we don't clash with any other deadline: @kouroshD @prashanthr05 @GiulioRomualdi @isorrentino

**Comment by prashanthr05** [comment]
> > After today's meeting, it came out that we would need quite some days of downtime in order to carefully inspect all the parts and at the same time install the battery. Keeping some margins, **one workweek** (probably less) should be sufficient.
> > Our proposal is to start off this maintenance the **first week of March 01-05/03** (we cannot do that before, unfortunately).
> > Does it work for you?
> 
> Thanks @pattacini, I think it should be ok. In any case, let me ping other people involved with the experiments to make sure we don't clash with any other deadline: @kouroshD @prashanthr05 @GiulioRomualdi @isorrentino

No problem for me. Thanks @S-Dafarra.

**Comment by pattacini** [comment]
Today we have begun the maintenance of iCub 3, as agreed.
However, and as we have communicated to @S-Dafarra, the required downtime will extend to the next week.

**Comment by pattacini** [comment]
@S-Dafarra please find attached the report of the mech activities, as promised.

[iCub 3 – Deep HW maintenance.pptx](https://github.com/robotology/icub-tech-support/files/6129287/iCub.3.Deep.HW.maintenance.pptx)

When the robot will be back operational, we could check if this issue can be marked as solved or not.

**Comment by S-Dafarra** [comment]
> @S-Dafarra please find attached the report of the mech activities, as promised.
> 
> [iCub 3 – Deep HW maintenance.pptx](https://github.com/robotology/icub-tech-support/files/6129287/iCub.3.Deep.HW.maintenance.pptx)
> 
> When the robot will be back operational, we could check if this issue can be marked as solved or not.

Thanks a lot!

**Comment by pattacini** [comment]
@S-Dafarra a quick update on this.

We've been experiencing a bunch of problems while checking the calibration of the iCub 3. Essentially, due to the quadrature encoders that got dirty during the remounting, unfortunately (although we paid attention), we had the following shaking on 3 joints:

https://user-images.githubusercontent.com/3738070/111164787-ad139200-859e-11eb-8086-20543f9a4bbb.mp4

https://user-images.githubusercontent.com/3738070/111164931-ca486080-859e-11eb-992c-3844bcaa3824.mp4

https://user-images.githubusercontent.com/3738070/111164695-99682b80-859e-11eb-9339-8f90014107c2.mp4

👉🏻 We managed to solve the first two problems as per the following video

https://user-images.githubusercontent.com/3738070/111165188-0a0f4800-859f-11eb-9486-a4c3e917083d.mp4

The left hip yaw is still missing and to sort it out we'd be required to unwire the boards again. As it can be easily figured out, this will take some time. Today and tomorrow, we will thus continue working on this.

**Comment by pattacini** [comment]
cc @salvi-mattia @davidetome @simeonedussoni

**Comment by S-Dafarra** [comment]
Thanks for the update @pattacini! The right hip roll keeps being a problematic joint :grin: Did you have to tune the joints? Maybe the previous set of gains is no more valid. Back in time we had to use a set of gains on the right that was consistently higher than those on the left:
- right: https://github.com/robotology/robots-configuration/blob/3c71e095a7c1c6b5463518dcbe96746430e588b6/iCubGenova09/hardware/motorControl/right_leg-eb10-j0_1-mc.xml#L50
- left https://github.com/robotology/robots-configuration/blob/3c71e095a7c1c6b5463518dcbe96746430e588b6/iCubGenova09/hardware/motorControl/left_leg-eb6-j0_1-mc.xml#L51

**Comment by pattacini** [comment]
Actually, we didn't look at the PID gains (yet); so those are the "old" values you were used to.
Please, @davidetome correct me if I'm wrong.

The remaining shaking is on the left hip yaw, not on the right hip roll and should be due to the dirty (freaking) encoders.

The idea is to finish up as soon as possible the cleaning of this optical encoder and the calibration of the 2 missing magnetic AMO (cc @simeonedussoni), quickly check that all the joints start up correctly, and then decide whether we can keep the robot to perform the quadrature encoders test or give the robot back to you and arrange for such a test one early morning by your system setup (@davidetome).

(Re-)tuning the PID is a task we would like to explore with you guys, in this extent.

**Comment by S-Dafarra** [comment]
> (Re-)tuning the PID is a task we would like to explore with you guys, in this extent.

No, no absolutely, I was not asking to retune them. I am totally ok with the old ones. I was just wondering if you needed to change any value.

**Comment by pattacini** [comment]
>maybe the "old" gains were too high introducing oscillations.

Yes indeed, that was one possibility we explored together w/ @davidetome. We basically removed the I and halved the P but the shaking was still present. By cleaning up the quadrature encoders, we managed to solve the problem on 2 out of 3 joints.
The last joint is still under maintenance (it's difficult to reach the cleaning hole).

**Comment by pattacini** [comment]
🧹 We cleaned up the **left hip yaw** and this sorted out the problem we reported above:

https://user-images.githubusercontent.com/3738070/111329899-c3d5e980-866f-11eb-9d3d-f83902f36c49.mp4

iCub 3 is fully operational now ✔

**Comment by pattacini** [comment]
Hi @S-Dafarra 

I know you're still getting along with the iCub 3 after all this long interlude 😀but do you have already any feedback on this regarding the weird noise?

**Comment by S-Dafarra** [comment]
> Hi @S-Dafarra
> 
> I know you're still getting along with the iCub 3 after all this long interlude  but do you have already any feedback on this regarding the weird noise?

We managed to run it once on Thursday. We did not notice any weird noise anymore. The only noise we could hear was the normal one related to the belt moving.

**Comment by pattacini** [comment]
Thanks for the feedback @S-Dafarra 👍🏻 
Closing then, feel free to open it up again if required.
