### ISSUE TITLE
Missing boards (ethernet chain broken)

### ISSUE THREAD

**Issue by randaz81** [robotology/icub-tech-support#1109]
Request for assistance for CER02 SN001 (currently located in Erzelli).
Cannot ping boards 10.0.1.7 and 10.0.1.10 @emilianob80

**Comment by emilianob80** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/53729815/112616605-39864600-8e24-11eb-8729-c238aa86d45c.png)

**Comment by emilianob80** [comment]
@violadelbono probabilmente il problema lo risolvi verificando :  

cavo eth E6 in uscita da scheda 10.0.1.6 su wrist 

cavo eth E6 in ingresso su scheda 10.0.1.7 su mano

da FirmwareUpdater si vede chela catena eth è collegata fino alla 10.0.1.6 compresa

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/53729815/112617927-e1504380-8e25-11eb-9eca-e128343402be.png)


cc: @randaz81

**Comment by violadelbono** [comment]
Cable eth 6 was broken at the exit to board 10.0.1.7
This is due to the sliding of the electrical cables inside the cover since there is a very little space. 
The problem has been solved by restoring the cable and putting zip ties in order to flatten the cables as much as possible.

@randaz81 please open a new issue for the shoulder problem. Thanks!
