### ISSUE TITLE
yarprobotinterface does not start

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-tech-support#1117]
Sorry @EliseiFrederic but I had to react immediately and purge the malformed issue number `0`.
Can you please fill in the details hereinafter again?
Sorry for the inconvenience.

**Comment by EliseiFrederic** [comment]
yarprobotinterface refuses to start. Seems related to can [0] (face):

...
[ERROR]sharedcan [0] thread:0 msg:91 joint:2 timed out
[ERROR]getFirmwareVersion: message timed out
[ERROR]Unable to read firmware version
...
[ERROR]sharedcan [0] thread:0 msg:91 joint:3 timed out
[ERROR]getFirmwareVersion: message timed out
[ERROR]Unable to read firmware version 
[ERROR]sharedcan [0] thread:0 msg:91 joint:4 timed out
[ERROR]getFirmwareVersion: message timed out
[ERROR]Unable to read firmware version 
...
[ERROR]sharedcan [0] thread:0 msg:91 joint:5 timed out
[ERROR]getFirmwareVersion: message timed out
[ERROR]Unable to read firmware version
...
[ERROR]
[ERROR]###################################################################################
[ERROR]###################################################################################
[ERROR]
[ERROR]  It has been detected that your control boards are not using the same
[ERROR]  CAN protocol used by iCubinterface. iCubInterface cannot continue.
[ERROR]  Please update your system (iCubInterface and/or your control board firmware.
[ERROR]  For further information please visit: http://wiki.icub.org/wiki/Firmware
[ERROR]
[ERROR]###################################################################################
[ERROR]###################################################################################
[ERROR]
[ERROR]checkFirmwareVersions() failed. CanBusMotionControl::open returning false, 
[yarprobotinterface_log.txt](https://github.com/robotology/icub-tech-support/files/6281620/yarprobotinterface_log.txt)

**Comment by EliseiFrederic** [comment]
I also inspected the "replies" on the esw can bus
[canloader_report.txt](https://github.com/robotology/icub-tech-support/files/6281630/canloader_report.txt)
:

**Comment by EliseiFrederic** [comment]
Here is what was detected on can bus 0:
![can_0](https://user-images.githubusercontent.com/15633142/114098623-e7343300-98c1-11eb-93a2-1de3f4dd94ce.png)

**Comment by EliseiFrederic** [comment]
Indeed, removing the 3 faces references in icub_all.xml for our robot
has allowed to run yarprobotinterface.

**Comment by EliseiFrederic** [comment]
So, we opened the head for a (random) visual inspection for a wire/connector problem. We didn't see any... but since we closed the head again, we couldn't run yarprobotinterface (other errors for other canbus).
Should we search for a specific connector or wire ? Or do you suspect another error ?

**Comment by EliseiFrederic** [comment]
### CONTEXT
The head has been opened several time because of the motherboard battery problem, and the motherboard is powered on continuously 5 days/night per week until we can solder a new battery (we aimed at finishing the current experiment on April the 20th)

**Comment by violadelbono** [comment]
Hi @EliseiFrederic, 

Looking at the boards FW version of your robot (v2 -talking head) it seems that the versions are correct. You can find them here:

https://icub-tech-iit.github.io/documentation/icub_firmware/associated-firmware/associated-firmware/#icub-v2-talking-head

I am only confused by board 15 (which in my documentation should be 9) where the protocol is not detected. The whole problem could be that the board doesn't detect the protocol.

- Did you do any maintenance on that board?
- Do you know why the ID is 15 instead of 9?

Anyway I think you can try to flash the fw again on that board and see if the situation changes.

**Comment by maggia80** [comment]
yes, I think that the board with ID=15 got an error in the flash area where this ID is saved. And its ID changed from 9 to 15. It could be a failure in the FLASH. Since we are sending you a spare part for the eyelids, we may add an MC4 board.

**Comment by EliseiFrederic** [comment]
Thanks @violadelbono & @maggia80 
No maintenance on any board, nor firmware flashing for ages on our side (last flashing was done remotely by @randaz81 & staff). If that helps,I will post of what the canloader scanned for ID9 and ID15.

Should we try to flash ? If yes, can you point me to the procedure ?
Should we disconnect/disactivate the board to continue our experiments (that don't use skin) ? If yes, where can we find it ?

Thanks again

**Comment by EliseiFrederic** [comment]
![can_9](https://user-images.githubusercontent.com/15633142/114158027-8d188980-9924-11eb-8c4c-a0a4dc52d536.png)
With the canloader menu, I was proposed ID 0 to 9. Not ID15

**Comment by maggia80** [comment]
@EliseiFrederic the problem is that if you try to change the ID of a board with ID=15 it may cause all the board to change their ID to 9, since 15 is the broadcast ID. I'm checking if we have a spare card that we can send you for free.

**Comment by EliseiFrederic** [comment]
Would be fine, thanks !

**Comment by EliseiFrederic** [comment]
Dear all,

I see the expedition is imminent. Good news :-)

We try to prepare for the repair (never did one such). Were will we find the MC4 ? What will we have to dismantle ?
I tried to follow the links for the v2.3 in [iCub Tech Docs](https://icub-tech-iit.github.io/documentation/icub_wiring/icub2_x/)  but they point to nowhere

Thanks in advance

**Comment by violadelbono** [comment]
Hi @EliseiFrederic,

Sorry for the inconvenience, we will fix the website soon.

This is the repository where you can download the electrical schematics: [https://github.com/icub-tech-iit/electronics-wiring-public/tree/master/icub2/icub-2.3.0-talkinghead/pdf](https://github.com/icub-tech-iit/electronics-wiring-public/tree/master/icub2/icub-2.3.0-talkinghead/pdf)

In particular, in iCub 2\_2.3.0\_XXXX\_Logic.pdf you will find the schematic of the head (last page). The MC4 board will come already programmed and with the correct ID 9. What you need to do is to first disconnect all the cables attached to it and replace the old one 0B9 with the new one. The schematic will help you to remember the correct position of every cable attached to the board, but I also suggest to take a preliminary picture before disconnecting, since sometimes it is difficult to recognize all the cables.

![](https://user-images.githubusercontent.com/61685519/114832066-5c29d000-9dce-11eb-967a-2303d9dedb3b.png)

In the Motor&Board placement pdf I see that that board is below 0B7 and 0B1 so unfortunately you need to move them by detaching the stand-offs in order to create space to access the 0B9. 

![](https://user-images.githubusercontent.com/61685519/114832836-3c46dc00-9dcf-11eb-9d12-406274cf86df.png)

![](https://user-images.githubusercontent.com/61685519/114834076-83819c80-9dd0-11eb-84c7-21a45efe455a.png)

**Comment by EliseiFrederic** [comment]
Dear all,Thank you for the files & advices. The board has arrived, and I'll try to find some competents people to assist me (or the reverse...) for the repair task !Thanks again,Frédéric, Loriane, and GérardP.S. Thank you also for the pair of eyelids pairs. I'll probably ask you later how to prepare/screw the two parts together without breaking the thin plastic

**Comment by EliseiFrederic** [comment]
Dismantling was ok, except for some nylons screws / hex spacers that we will have to source and replace (M2,5 ?). Looks like they don't like heat and years that much!

**Comment by EliseiFrederic** [comment]
Good news, with the new board the robot can start and calibrate as before.
Thanks for the advices, support and already programmed board :+1: !
