### ISSUE TITLE
Cannot start R1: missing boards problem

### ISSUE THREAD

**Issue by randaz81** [robotology/icub-tech-support#1143]
### Device name 🤖

R1SN003

### Request/Failure description

On some occasions, yarprobtinterface fails to start due to missing boards.

### Detailed context

When this happens, we cannot ping boards that are after the board with the ip 10.0.1.12 in the chain (see picture below).
We thus think that a cable connection is somehow damaged. 
To investigate the problem, we removed the cover of the left arm, but visual inspection gave us no hints.

### Additional context

![MicrosoftTeams-image (22)](https://user-images.githubusercontent.com/2869969/121341804-501b4400-c921-11eb-99f9-a5da23d19311.png)

**Comment by lnobile** [comment]
Robot seems to work now, the problem is in the 10.0.1.8 board that sometimes is not powered (we noticed this because of flickering led on the board). After moving the board with a finger it doesn't shut down anymore. It could be a flimsy cable issue but now seems to work, even after moving the board and connected cables.
I didn't closed the covers to let you investigate more deeply into the problem.

**Comment by lnobile** [comment]
@Arya07

**Comment by violadelbono** [comment]
Hi all,

There were 2 cables loose connected to board EMS12.
We fixed them and mounted the covers.
