### ISSUE TITLE
Fingertip skin not working

### ISSUE THREAD

**Issue by matejhof** [robotology/icub-tech-support#1180]
### Device name 🤖

iCubPrague01

### Request/Failure description

The skin on the right hand fingertip of the thumb was not working (June 2021). As a consequence, no skin on the right hand was not working, which could be resolved by removing the thumb jumper from the back of the wrist - then everything apart from the thumb skin was working.
Yesterday, we replaced the thumb fingertip using the new one provided by IIT and resoldered the connections. 

Unfortunately, after this operation and putting back all the jumpers, none of the hand skin (5 fingertips and palm) works.
After removing the thumb jumper, the palm, litle finger and middle finger skin work, while the thumb and newly also the ring finger and index finger skin do not work.
If only the thumb jumper is in place, the thumb still does not work.
(@0xbeda is in charge on our side.) 

### Detailed context

Thumb fingertip before replacement:
![IMG_20210825_181242](https://user-images.githubusercontent.com/6461061/130936124-72cc79b5-e56c-4764-907d-3e9f5c2a105b.jpg)
Thumb fingertip after replacement:
![IMG_20210825_165144](https://user-images.githubusercontent.com/6461061/130936137-3e610969-486d-4b9f-9191-8c46f19a989f.jpg)

**Comment by Uboldi80** [comment]
Hy @matejhof 
Sorry, did you tried to replace the fingertip thumb with the other spare we had send to you?

let me know

**Comment by matejhof** [comment]
Hi,
no we did not try that. The soldering is a bit delicate and the wires are getting shorter with every iteration...

**Comment by Uboldi80** [comment]
However, I would suggest you replace the R0 fingertip with the second replacement we sent you.
after it is replaced, the best thing to do is to remove all FTC connections apart from the thumb one and start skin manager to test palm and thumb.

let me know

**Comment by matejhof** [comment]
This is still active. @0xBEDA will hopefully try the above-recommended solution soon.

**Comment by matejhof** [comment]
We replaced the thumb fingertip with the other that was sent to us. Now the thumb fingertip is working. 
However, the ring and index finger are still not working when all the jumpers are in place. 
(Note that these fingers were initially working when the robot was delivered - see above - and we did not replace these fingertips.)
When the thumb jumper is removed, the ring and index finger are still not working. 
Thanks!

**Comment by Uboldi80** [comment]
Hy @matejhof 
do you have checked the wires of these fingertip on the board,? All 4 wires ares soldered on the board?
have the ftc connectors been placed in the right direction?
or 3 dots towards the outside and 4 towards the inside.
Have these 2 non-working fingertips been removed and replaced or have they never been touched?
I ask you because if they have been touched you should check the wiring from the fingertip to the board.
another thing:
Were all the replacements that were made with the setup turned off?
removing and putting the ftc connectors during operation sometimes does not give the right feedback, so for example, if the setup was started without 2 ftc connector and during the session using the skin, the 2 missing ftc are replaced and the calibrate is performed however, they may not work.
To be sure of the functioning or not of those fingertips, I suggest to start the setup (at least the engines) and obviously restart the skin manager and GUI session with all the ftc mounted.
in this way you will be sure of the situation of the fingertips.

**Comment by 0xBEDA** [comment]
Please see my comments
> do you have checked the wires of these fingertip on the board,? All 4 wires ares soldered on the  board?

Yes all the wires seem to be soldered

> have the ftc connectors been placed in the right direction?

Yes

> Have these 2 non-working fingertips been removed and replaced or have they never been touched?

No, non-working finger tips haven't been touched

> Were all the replacements that were made with the setup turned off? 

Sure

> To be sure of the functioning or not of those fingertips, I suggest to start the setup (at least the engines) and obviously restart the skin manager and GUI session with all the ftc mounted.
in this way you will be sure of the situation of the fingertips.

After plugging in all the ftc "jumpers" complete power cycle has been performed (hard, even the power supply was turned off), after complete restart the situation is the same.

I'm curious if some measurements with scope and/or logic analyzer could be helpful. There are some testing points/pads on the upper side of the jumpers, probably there could be some signals (i2c ?)

**Comment by matejhof** [comment]
Hi @Uboldi80, how do you suggest to proceed? Thank you! 
Btw., next Wednesday, Nov 24, in the morning, we have an online mechanical maintenance training. There will be a videoconference set up, so there is a possibility to use this to make progress on this front.

**Comment by Uboldi80** [comment]
Hy @matejhof 

Yes, i think is possible to try ti fix the fingertips during or after the trial session.

cc @maggia80

**Comment by Uboldi80** [comment]
@matejhof 
Sorry, meanwhile, do you want share some photo of the situation?

- some photo of back of palm without the cover to investigate in advance the problem
- some photo of fingertip that you soldered 
this could be help to know the problem.

Thanks

**Comment by 0xBEDA** [comment]
![IMG_20211102_173154](https://user-images.githubusercontent.com/73338377/142444262-a95ccb0c-b54c-4f98-ba78-44fff981412a.jpg)
![IMG_20211102_181558](https://user-images.githubusercontent.com/73338377/142444272-165de488-2052-4fec-a630-21c6568af6ad.jpg)
Please see the requested photos. I would like to mention, that replaced thumb is working now, the problem is on the  ring and index finger which were not touched. Visual inspection of wires, connector, etc. doesn't show us anything broken.

**Comment by 0xBEDA** [comment]
The missing thumb jumper is just from testing, it was returned back. All the jumpers were checked and nothing wrong was found

**Comment by Uboldi80** [comment]
ok @matejhof 

sorry, can you remove the nails of the right hand?
after this i ask to you to run the setup (without the nails)
and check the fingertip skin trough the skin gui.

**Comment by 0xBEDA** [comment]
What do you mean by "remove nails"? Just unplug the jumpers? Unsoldering is quite risky operation, I guess.

**Comment by Uboldi80** [comment]
No, simply remove the screw that blocks the nail on the finger.
i would to try this, cause sometimes the nails could be hidden the problem.

![1637580277440](https://user-images.githubusercontent.com/80786976/142853453-8574301e-d534-4c91-94d4-901eacd41739.jpg)

**Comment by 0xBEDA** [comment]
Ok, I see. Thanks

**Comment by Uboldi80** [comment]
after the meeting in this morning we have seen that the problem in the right hand is due to 2 fingertips:

RO INDEX and R2 ring finger

@Fabrizio69 we need to ship to @matejhof  this 2 spare parts.

**Comment by Fabrizio69** [comment]
Hi @Uboldi80 , here the components involved:
1 piece cod.1465.7 - iCub, subassembly - Fingertips for right hand, thumb or index finger, address 0, with lycra
1 piece cod.1467.7 - iCub, subassembly - Fingertips for right hand, ring finger, address 2, with lycra
are available in stock, we can proceed.

**Comment by Uboldi80** [comment]
Thanks @Fabrizio69

**Comment by matejhof** [comment]
Fingertips have arrived, we have replaced them and everything seems to be working now! 
Thanks @Uboldi80 , @Fabrizio69 , @0xBEDA and everyone!
Closing.

**Comment by Uboldi80** [comment]
yahooooo!!! very cool @matejhof
