### ISSUE TITLE
iCub not moving after calibration

### ISSUE THREAD

**Issue by cedricgoubard** [robotology/icub-tech-support#1182]
### Device name 🤖

iCubLondon01

### Request/Failure description

Hello,
I just calibrated our iCubLondon01 following the instructions provided [here](https://github.com/robotology/icub-tech-support/files/7030963/TP_ROBOT_CALIBRATION.pdf).
Now, all the motors stopped moving.

### Detailed context

Here are the steps I followed for calibration:
- I pressed the fault button
- I launched `yarprobotinterface`
- I launched `yarpmotorgui`
- I filled the `xls` file with the values for the different encoders
- I generated the `xml` files and placed them in `/exports/code/robotology-superbuild/build-icubunicorn/install/share/ICUBcontrib/robots/iCubLondon01/`, which is the repository returned by `yarp resource --from general.xml`
- I shut down the robot (`pc104` and motors), released the fault buttons, and turned it back on

Now, here are the issues I am facing:

- `iCub` does not move in standard position when I run `yarprobotinterface`
- I cannot move the motors using `yarpmotorgui`
Apart form that, everything seems to run correctly: `yarprobotinterface`, `iKinCartesianSolver` and `wholeBodyDynamics` all run, and the usual ports are created.

`yarprobotinterface` does raise warnings and errors, but I cannot really make sense of them. Here are [the logs.](https://github.com/robotology/community/files/7056168/yarprobotinterface.log)

Here is what `yarpmotorgui` looks like:
![image](https://user-images.githubusercontent.com/40461909/130963120-63e8f9eb-9695-46b2-a049-4b6a4798b591.png)

I tried changing the `idle` mode to `position`, but nothing happens.

Do you have any idea what might have gone wrong?
Any help would be greatly appreciated.

### Additional context

Moved from **https://github.com/robotology/community/discussions/542**

**Comment by davidetome** [comment]
Ciao @cedricgoubard ,

 did you follow this steps in order to get raw data to put in the `.xls` file?

- Power off the motors
- Edit the `general.xml` file setting to `false` the `skipCalibration` and `useRawEncoderData` params
- Power on the motors
- Press the external fault button and run `yarprobotinterface` (you' ll need to press `enter` few times as `yarprobotinterface` asks)
- Read the raw values from the `yarpmotorgui` and put them in the `.xls` file as described in the procedure
- Power off the motors
- Edit the `general.xml` file setting to `true` the `skipCalibration` and `useRawEncoderData` params 
- Power on the motors
- Release the external fault button and run `yarprobotinterface`

**Comment by cedricgoubard** [comment]
Hi @davidetome,
Yes, that is what I did. The only difference is that once I entered the values in the `.xls` file, I clicked on `Generate All` and I moved the resulting `.xml` files in the robot's folder.

If you think I did something wrong, I can try to do it again.

**Comment by davidetome** [comment]
> If you think I did something wrong, I can try to do it again.

The important step is to power off/om the boards after the `general.xml` file is edited.
I looked at the log you provided above, there are few errors regarding buffer overrun:
```bash
[ERROR] recv buffer overrun ( 500 >  500)
```
I'm going to ask to my peers who work on the `firmware` and let you know

**Comment by davidetome** [comment]
Ciao @cedricgoubard ,

 just to inform you that people working on the FW are off this week, they'll back starting next week

**Comment by davidetome** [comment]
Hi @cedricgoubard ,

 it occurred to me that you should also manually copy these 2 lines (for each part) in the correspondent `hardware/motorcontrol/` file
 
![Screenshot-20210902165230-1264x1139](https://user-images.githubusercontent.com/6638215/131866261-5b22652d-60eb-420b-8aed-434d34af22e7.png)

I will add this point to the procedure that I'm going to publish on our documentation site

cc @maggia80 @pattacini

**Comment by cedricgoubard** [comment]
Hi @davidetome,
Ok, I'll keep trying to figure out what's wrong until then. 
I used the `FirmwareUpdater.script.update.all.sh` script to update the firmware, maybe something went wrong then? Is there any way that I can get a list of the expected firmware versions? 

Also, I received a notification on the Github app that you replied something about adding lines to the `.xml` files generated by the calibration, but I can't find it here... Did you delete it?

**Comment by davidetome** [comment]
Hi @cedricgoubard ,

 I looked at the files generated from the `xls` file and, as anticipated, I found some issues.
Since the `xls` file is very "old" and no longer maintained few parameters has changed the name and others have been added.
So we can work around the problem following some manual steps instead of using the macros inside the `xls`; in particular, you should do the following : 

- Revert to the upstream configuration files (you may save the `xls` file in another place before reverting so you have all new raw values you put in)
- Replace the `xls` file w/ the above saved 
- Manually copy only the highlighted lines below and paste them inside the corresponding `xml` file inside `calibrators` folder
 
![1](https://user-images.githubusercontent.com/6638215/131981019-0f64c138-f681-4584-b0ba-308841ccbf5a.png)

- Manually copy only the highlighted lines below and paste them inside the corresponding `xml` file inside `hardware/motorcontrol` folder

![2](https://user-images.githubusercontent.com/6638215/131981262-4eb7620f-1ae1-4bd5-a7b6-6f2996b12a05.png)

Obviously, you have to do the same for each robot part

cc @maggia80 @pattacini

**Comment by cedricgoubard** [comment]
Hi @davidetome,
`iCub` is moving again, thank you! 
However, I noticed that the [`xls` calibration file](https://github.com/robotology/robots-configuration/blob/master/iCubLondon01/iCub_Calibration_V1_3_1_iCubLondon01.xls) does not include any formula for the wrists; is that normal?

**Comment by davidetome** [comment]
> However, I noticed that the xls calibration file does not include any formula for the wrists; is that normal?

I think your iCub has the old wrist, w/o the absolute encoders (AEA), in this case, that's normal

**Comment by cedricgoubard** [comment]
Great then, thank you again for your help!
