### ISSUE TITLE
iCubGenova04 broken tendon right thumb

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1190]
### Device name 🤖

iCubGenova04

### Request/Failure description

Broken right thumb tendon.

### Detailed context

Right thumb tendon broke as soon as I started the yarprobotinterface, in particular while the hand calibration.

cc @Uboldi80 @S-Dafarra

**Comment by Uboldi80** [comment]
the problem of the broken tendon was probably caused by the gearbox which turned very badly.
this in fact involved the subsequent tearing of another tendon of the same joint.
furthermore, the encoder reading was incorrect and the joint always started in NOT CALIBRATED STATUS, even though this joint had been calibrated at least 3 more times.
the problem was due to the ground of the connector which was uncovered and was going to touch another cable of the connector altering the values continuously.

**Comment by S-Dafarra** [comment]
I guess there are still issues with the encoders. At startup, this time the oppose joint went to the other end a couple of times, reading around 140deg. After a few startup, another tendon got broken

![image](https://user-images.githubusercontent.com/18591940/134053822-6bdfd9b8-ff87-4c58-8bf4-d01971d849f0.png)
