### ISSUE TITLE
Can't run initialization file after installing new live USB on iCub

### ISSUE THREAD

**Issue by omardarwishokd2** [robotology/icub-tech-support#1213]
### Device name 🤖

iCubUrbana01

### Request/Failure description

We created a new live usb and complied it. We aren't able to run the initialization file.

### Detailed context

RobotName: iCubUrbana01
Yarp: 2.3.22
iCub: 1.1.13

Hello,

We have had some trouble trying to run the icubSafe_nolegs.ini file. We receive the following error for both left and right arms when we do:

code: iCubInterface --config icubSafe_nolegs.ini
Error: Icub/cartesianController/right_arm: Checking if cartesian solvervartesianolver/right_arm is alive ……. Not yet

Background:
Initially we received an error: "no route to host" when trying to connect to PC104 via ssh. Following some of the discussions here, we decided to create a new live usb per some if the recommendations. 
We used the following link to create the bootable USB: https://icub-tech-iit.github.io/documentation/icub_operating_systems/pc104/the-icub-live-installation/

We installed the pc104-image-oc as it was what was installed on the old live USB.

We used the following link for the compilation:  http://wiki.icub.org/wiki/Compilation_on_the_pc104_old

Please let me know if there are more info that I can provide to help resolve this issue.

Regards,
Omar

### Additional context

One thing to add:
When we had the old live USB, we were able to start an instance of yarpserver before we ssh onto PC104 with no problems, but now, we need to create the instance of yarpserver after we ssh into PC104.

_No response_

**Comment by pattacini** [comment]
Hi @omardarwishokd2 

>code: iCubInterface --config icubSafe_nolegs.ini
Error: Icub/cartesianController/right_arm: Checking if cartesian solvervartesianolver/right_arm is alive ……. Not yet

This actually is not an error but rather some info issued by the Cartesian Controller Server, which is unable to find the Solver part to connect to. The info has been made clearer quite [some time ago][yinfo].

Then, you should run the solver component to let the server proceed successfully. However, the robot can be still used without the Cartesian server.

Learn more about the Cartesian Interface and how to get it started by browsing our [documentation][cart-doc].
Other relevant resources are hosted at our [community hall][community-hall].

---

That said, I can't help but point out how your SW system is very old and we cannot give much support for it.
Just to make an example, the `iCubInterface` has been eventually [deprecated 5 years ago][icubif-deprecated] and got replaced by the more modern `yarprobotinterface` deployer.

Therefore, try to check whether you can continue working along the path you chose so far, but also consider upgrading the robot system to our latest [distros][distros]. It won't be an easy undertaking for sure, as you will certainly come across a bunch of snags and kinks here and there, mostly due to the old HW equipping the robot.

Nonetheless, very recently, @cedricgoubard was quite successful in achieving exactly this with his `iCubLondon01`. Here's below a list of issues and requests he made to us:
- https://github.com/search?q=org%3Arobotology+author%3Acedricgoubard&type=issues
- https://github.com/search?q=org%3Arobotology+author%3Acedricgoubard&type=discussions
- https://github.com/search?q=org%3Aicub-tech-iit+author%3Acedricgoubard&type=issues

He also contributed to our [**`icub-tech-iit.github.io/documentation`**][icub-tech-iit-doc] by providing the guide for building an up-to-date [32-bits version of the iCub LIVE OS][32bitsLive] for supporting our distros.

Alternatively, you may also think of sending back to us your iCub so that we can renew it in terms of HW and/or SW, pretty much as we have done with `iCubNancy01` and have been doing to `iCubDjion01` (formerly known as `iCubLyon01`). To this end, you may contact us for further details.

Hope this helps out.

cc @maggia80 @Fabrizio69 @andreaderito

[yinfo]: https://github.com/robotology/icub-main/blame/f10dacdf01c480c340e4982ee3730c91f21a5f57/src/libraries/icubmod/cartesianController/ServerCartesianController.cpp#L2209-L2210
[cart-doc]: https://robotology.github.io/robotology-documentation/doc/html/icub_cartesian_interface.html#sec_cart_dependencies
[community-hall]: https://github.com/robotology/community/discussions?discussions_q=cartesian+solver
[icubif-deprecated]: https://github.com/robotology/icub-main/commit/c6038729c9a3401a2d047a20c756867c35692944
[distros]: https://icub-tech-iit.github.io/documentation/sw_versioning_table/
[icub-tech-iit-doc]: https://icub-tech-iit.github.io/documentation
[32bitsLive]: https://icub-tech-iit.github.io/documentation/icub_operating_systems/pc104/icub-live-32bits/
