### ISSUE TITLE
Problem powering the robot with iCub batteries

### ISSUE THREAD

**Issue by vpunithreddy** [robotology/icub-tech-support#1218]
### Device name 🤖

iCubGenova04

### Request/Failure description

The robot iCub Genova-04 is not able to power up using the iCub batteries

### Detailed context

We tried to power the robot using the batteries, There is some issue that the robot does not get power from the batteries. Also, the battery does not display any light that is supposed to indicate the charging status when the black button on the battery is pressed.

**Comment by Uboldi80** [comment]
Hy

Today checked the batteries:
both the batteries are discharged, in particular the battery with the new B-MON is completely down as you can see in the image below.
i have connected the battery to the battery chargher so that it load.

![IMG_20211013_083003](https://user-images.githubusercontent.com/80786976/137079929-a73b9b50-13a6-4217-b8dd-830c5bd78e1f.jpg)
