### ISSUE TITLE
iCubGenova01 - Right thumb proximal cable broken

### ISSUE THREAD

**Issue by Arya07** [robotology/icub-tech-support#1236]
### Device name 🤖

iCubGenova01

### Request/Failure description

The cable of the right thumb proximal broke up. The robot was not performing any action. 

### Detailed context

The cable of the right thumb proximal broke up. The robot was not performing any action.

**Comment by gsisinna** [comment]
On Friday (November 19) the proximal thumb cable was replaced and during the operation the distal thumb cable was also replaced as it was worn to the limit.

Since it's not the first time that the same problem occurs, thanks to @GiacomoVassallo13  support, several sheaths were analyzed and replaced and the tendons were tensioned with the utmost care.

At the end of the intervention, towards the last step of the calibration, it seems that the head has stopped working. It was therefore necessary to proceed for several hours with the recreation of a USB for the head, which obviously has been corrupted for some reason.

At the end of the creation of the head was performed the usual calibration procedure for the thumb using the excel file, and was opened a further issue to track the problem of pc104.

cc @Uboldi80 @GiacomoVassallo13 @xEnVrE
