### ISSUE TITLE
iCub right wrist not calibrated

### ISSUE THREAD

**Issue by lunagava** [robotology/icub-tech-support#1243]
### Device name 🤖

iCub[Genova][02]

### Request/Failure description

After issue #1240, we noticed that the home position of the wrist is not the correct one. 

### Detailed context

The wrist is not straight, it is looking down a little.

**Comment by gsisinna** [comment]
In order to bring the system back to a working state, deltas were added to joints 5 and 6 of the right arm. The calibration type is still the old one (type 3) for these joints. It would be useful to update the calibration type 12 in the near future.
Now the wrist has zero to an acceptable position for shooting and normal operation.
