### ISSUE TITLE
iCubErzelli01 - joint 4 calibration drift (right arm)

### ISSUE THREAD

**Issue by gsisinna** [robotology/icub-tech-support#1270]
### Device name 🤖
iCubErzelli01

### Request/Failure description
After several calibrations of joint 4 we noticed a shift of the zero value, and consequently an incorrect position of the joint.

### Detailed context
We think there is a problem with the motor encoder. Further investigations are needed. 

### Additional context

**Comment by gsisinna** [comment]
cc @ddetommaso

**Comment by Uboldi80** [comment]
Below the detail of joint 4 motor:

![image](https://user-images.githubusercontent.com/80786976/148512109-2c1fb7bd-6bd7-40b7-a620-f261b64e7e52.png)

I think that the problem of the shift position after every calibration could be caused by the 2 granis in the motor shaft:

![image](https://user-images.githubusercontent.com/80786976/148513372-dd6c9471-23bd-453d-9182-f6ba65468185.png)

**Comment by Uboldi80** [comment]
we standing @ddetommaso to schedule the intervention after the the experiment.

**Comment by emilianob80** [comment]
@Uboldi80 After a check I found the flat cable interruption. I proceeded to replace the interrupted part by joining a new flat. The motor and encoder are working properly
![IMG_20220221_064714](https://user-images.githubusercontent.com/53729815/154896647-ef9d2c42-3685-4462-b95f-16143133146b.jpg)

**Comment by Uboldi80** [comment]
the joint has been thoroughly tested and works well.
