### ISSUE TITLE
iCubErzelli02: left pinky joint desn't calibrate and right arm strain connection issue

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-tech-support#1286]
### Device name 🤖

iCubErzelli02

### Request/Failure description

On the robot there are two issues:
1. the  left pinky joint doesn't calibrate
2. some times the joint of right arms go to hardware fault status because they don't receive the torque values.

### Detailed context

We report here the log:
1. 
```
[ERROR] Left_Arm_Calibrator : Timeout while calibrating 15
[ERROR] Left_Arm_Calibrator : set 5 : Calibration went wrong! Disabling axes and keeping safe pid limit
```

2. From the following images we deduce that the strain stops to send torque values for a bit of time.  Maybe it is due to a CAN cable issue when it is stretched or it is not well connected.

![Screenshot from 2022-01-20 15-03-54](https://user-images.githubusercontent.com/4233231/150530596-179030c9-0968-4dbf-97b0-0bd37e3c80ed.png)
![Screenshot from 2022-01-20 15-12-41](https://user-images.githubusercontent.com/4233231/150530600-04bcb1da-5c0f-45e0-80dc-ae9ccc24288a.png)
![Screenshot from 2022-01-20 15-03-45](https://user-images.githubusercontent.com/4233231/150530601-ef15e652-0f9e-436a-9cae-40dc00315ffa.png)

cc @lauracavaliere

**Comment by gsisinna** [comment]
After a long debugging session, several problems were identified and some of them were not directly attributable to the hardware.

1. The left pinky was wound upside down, so it was repositioned correctly and re-calibrated for optimal operation. It is now in green on the yarpmotorgui and has been tested to the limit.

2. Initially @Uboldi80 checked all communication lines and boards and replaced two connectors. However, the problem persisted and it seems to be due to the setup of the laptop used with the robot, recently replaced.

Thanks to the support of @Nicogene, we have further investigated the problem and discovered that the WholeBodyDynamics module opened and connected the ports correctly only if started from the head, but not from the yarpmanager of the laptop. 

It was then compiled the correct version of the superbuild also on the laptop (it seems that it was not the most recent) and now the module starts correctly without sending the joints of the arms in hardware fault when entering the compliant mode during the demo redball. 

cc @valegagge
