### ISSUE TITLE
The robot's 03 joint cannot be read

### ISSUE THREAD

**Issue by tKsome** [robotology/icub-tech-support#1308]
### Device name 🤖

iCubShenzhenS/N0.39

### Request/Failure description

After repairing the thumb of the robot, we found that the 03 joint motor of the robot was wrong.And there's no change in the encoder.After inspection, it was found that the two power lines of joint 03 were disconnected, and errors were still reported after re-welding.Looking forward to your reply.

### Detailed context

The damaged part is in the robot's right arm

### Additional context

![70d66f2df77af87ec6344f636cdfd9b](https://user-images.githubusercontent.com/28921533/155256482-9b14c953-af1e-4eb3-ab4e-a61cd09dc5cd.jpg)
![1821adf70b0156e90860459b12a25b4](https://user-images.githubusercontent.com/28921533/155256499-7f7ebb8a-a492-455e-a5ed-cb2eea4bf395.jpg)

**Comment by Uboldi80** [comment]
Good morning
the photo you sent related to the current situation?
that is, was the black cable from the hall sensor that should be soldered in the GND position re-soldered correctly?
since from the image on the motorgui that you sent, it seems that there is always a problem in the same point which is probably always due to a wire that has detached from the board with the hall sensor.
generally this can happen when the plastic shell near the shoulder is removed or reassembled which tends to be very wire and the risk is to tear some of it.
for this reason, when the plastic ones are removed and put back, it is necessary to be careful and slightly enlarge them during these operations.
check the hall sensor part of this joint again and try with tweezers to lightly pull the wires to make sure they are still soldered.
if there is glue to protect the welds, remove it carefully. The glue sometimes hides a wire that is actually no longer soldered to the pad.
let me know.

**Comment by Uboldi80** [comment]
also check the patch connector upstream of the hall sensor.
also in this case, I recommend to remove the glue carefully and check that the cables are still effectively crimped to the terminals by pulling them lightly with tweezers.

**Comment by Uboldi80** [comment]
verificare questo connettore oltre al sensore di hall

![1645602679013](https://user-images.githubusercontent.com/80786976/155279610-f8190c8f-406e-4f1f-a657-5a199d641587.jpg)

**Comment by SSSSamZhu** [comment]
Hi
I compared the two pictures, and I found that one of the encoder chip in the faulty picture seemed to have lost a resistor or capacitor. Could you please tell me the parameters of the relevant components?

**Comment by Uboldi80** [comment]
please tell me a photo of the board.

**Comment by SSSSamZhu** [comment]
![Inked企业微信截图_16456042713714_LI](https://user-images.githubusercontent.com/100264795/155284748-7d643e80-47d2-400c-9240-3afc7902a9fe.jpg)

**Comment by Uboldi80** [comment]
ok, yes the capacity is 10uF

![image](https://user-images.githubusercontent.com/80786976/155289099-192b5628-66ad-448b-95f2-edb90342b496.png)

**Comment by SSSSamZhu** [comment]
Okay！ I'll see if I can figure it out.Thanks.

**Comment by Uboldi80** [comment]
ok, good @tKsome 
after then you will be replaced the capacity, let me know.
THKS!

**Comment by tKsome** [comment]
The issue has been resolved and I will close the issue.Thanks
