### ISSUE TITLE
Repair iCubGenova02 - Left arm

### ISSUE THREAD

**Issue by sgiraz** [robotology/icub-tech-support#1316]
### Device name 🤖

iCubGenova02

### Request/Failure description

As I was restoring the robot to its state before the tests, I found that all the boards powered by the mc4plus of the left arm had stopped working (no longer powered).

### Detailed context

During the update of the FW (application layer) using the `FirmwareUpdater` something went wrong!
The `FirmwareUpdater` was stuck for more than a minute, but in the end, the application loaded for all the ems was the one expected.
Unfortunately, the `yarprobotinterface` didn't receive any response from the ems `eb02`, and no LED was blinking from the board of the left arm.

**Comment by emilianob80** [comment]
@Uboldi80 @gsisinna Left shoulder EMS4 electronic board replaced as required

**Comment by Uboldi80** [comment]
Following an EMS4 firmware update, 3 of the 8 boards failed.
Most likely I imagine that there is a problem on FirmwareUpdater, which during the update of several boards at the same time could have created problems with the bootloader of the same.
@sgiraz  what do you think?
Due to this problem, @gsisinna  and I had to extract the 3 EMS4 (EB1-EB2-EB3) from the back of the robot and reprogram them on the bench with the risk of creating damage to the setup.
I strongly urge you to verify why such a thing happened.

cc. @marcoaccame @Fabrizio69

**Comment by pattacini** [comment]
>Following an EMS4 firmware update, 3 of the 8 boards failed.
Most likely I imagine that there is a problem on FirmwareUpdater, which during the update of several boards at the same time could have created problems with the bootloader of the same.

Do we have any hypothesis to inquire @marcoaccame ?

**Comment by davidetome** [comment]
Honestly, in the last years, I didn't experience any bug-related issue of this kind; It happened the same to me sometimes but the  2 main issues were : 

- A power supply issue during the programming
- A mistake in the manual procedure of programming the updaterforBootloader/application 

Surely @marcoaccame could have any thoughts..

cc @pattacini @Uboldi80 @gsisinna

**Comment by marcoaccame** [comment]
> Following an EMS4 firmware update, 3 of the 8 boards failed.

I haven't ever seen such an extensive failure. It is difficult to say what has happened.
In any case, note the following:
- in case the update of an application on an ETH bord fails for any reason (in the past I surely tested: loss of link, of UDP packets, power off in the middle of an update, programming an ems w/ FW of an mc4plus) then you can recover by getting the ETH board in maintenance. You do that by switching off and on and then by sending a discovery straight away (in the first 5 seconds).
- reprogram the application, maybe one by one so that you can see what happens.

**Comment by Uboldi80** [comment]
Of course, the best thing is to take them one by one probably always, avoiding cumulative updates.
Unfortunately, however, when a problem like this occurs, it is necessary to remove the cards from the robot and put them on the bench, as they are no longer seen by FirmwareUpdater, consequently, it is necessary to remove them and attach it to the test equipment to burn the bootloader again.
