### ISSUE TITLE
The wrist yaw joints in iCubGenova09 tend to "diverge"

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1386]
### Device name 🤖

iCubGenova09

### Request/Failure description

We have noticed that the wrist yaw joints of iCubGenova09 tend to progressively loose calibration, leading to increasing calibration deltas.

### Detailed context

THe left wrist yaw joint reached a delta of 30deg: https://github.com/robotology/robots-configuration/blob/18d40d12fb86dfdc123721523c13fcec048665b1/iCubGenova09/calibrators/left_arm-calib.xml#L27, while the right 11deg https://github.com/robotology/robots-configuration/blob/18d40d12fb86dfdc123721523c13fcec048665b1/iCubGenova09/calibrators/right_arm-calib.xml#L28

I wonder if it has to do with the fact that the covers of the AEA encoder are often broken.

### How does it affect you?

It is not blocking. We often just recalibrate them, but it is suspicious.

**Comment by Uboldi80** [comment]
The left wrist had several problems, both mechanically and wiring.
the seat of the magnet holder (not the magnet itself) tended to move with respect to the rest of the wrist, albeit imperceptibly.
so i fixed the part and used locite 243 to ensure it doesn't move anymore.
![1657882736081](https://user-images.githubusercontent.com/80786976/179223458-3788414e-5454-47cf-a6a5-187912d31314.jpg)
Furthermore, the LS6 cable had a criticality near the connector, for this reason I decided to shorten it and restore the connector.![1657882736058](https://user-images.githubusercontent.com/80786976/179224088-b118e7b6-61dc-44a2-862c-b9d58c4eb470.jpg)
I recalibrated the pulse, and deleted the delta on the calibration file.
the setup has been tested and it seems that the problem is solved.

![1657882736070](https://user-images.githubusercontent.com/80786976/179224113-27386adb-014a-48e1-98ed-8b826b62b931.jpg)

cc. @S-Dafarra
