### ISSUE TITLE
Right arm failure and skin problems

### ISSUE THREAD

**Issue by rozliv** [robotology/icub-tech-support#1456]
### Device name 🤖

iCubPrague01

### Request/Failure description

Right forearm and wrist joints are not working (in HW fault).
Moreover torso skin and right hand skin are not working and right forearm and upperarm skin have many phantom activations. 
@matejhof

### Detailed context

While using, the right wrist fell into HW fault; after (several) restarts, neither the skin nor the joints are working. As can be seen in enclosed screenshots, the encoder values for these joints are really wild. 
The torso skin probably has not been working for a longer time. 

![Screenshot from 2022-11-07 12-42-18](https://user-images.githubusercontent.com/45361823/200305998-38cd0ef3-533f-4f59-988e-af5037668aa3.png)
![Screenshot from 2022-11-07 12-42-53](https://user-images.githubusercontent.com/45361823/200306007-1ae80ffe-654b-491d-961a-bc8f95bec47d.png)
![Screenshot from 2022-11-07 12-53-59](https://user-images.githubusercontent.com/45361823/200306015-e1360f0d-575f-49ea-a13c-5ab35642029a.png)
![Screenshot from 2022-11-07 12-55-08](https://user-images.githubusercontent.com/45361823/200306020-7d14fe43-7c4c-41e0-9efb-a70475f7e2b1.png)

**Comment by AntonioConsilvio** [comment]
Hello @rozliv , we received your issue and we will contact you soon with further updates.

cc @Fabrizio69

**Comment by matejhof** [comment]
Hello, 
is there any progress on this please? We have a timeline to run experiments...
Thanks!

**Comment by AntonioConsilvio** [comment]
Hi @matejhof and @rozliv I have some questions to better understand the problems with your robot.



The first one is: the parts of the robot that fell into HW error, if you try to move these joints manually with `yarpmotorgui` open (if you can put these joints in idle it should be better but it is not mandatory), does the encoder value change? Or is it always the same?



Another thing, you should use the `FirmwareUpdater` command on the iCub head (with -X because it is a graphical application), then select the first option and click Discover. Here you will be able to see all the electronic boards in your robot, so send us a screenshot of what you see.



If you have questions about either of these, write to us.

cc @Fabrizio69

**Comment by rozliv** [comment]
Hi @AntonioConsilvio, thank you for the response.
Encoders for joints 5 and 6 change values while moving, encoders for joints 4 and 7 change values even without moving (now the encoder for Joint 7 show around -2.4 million degrees and it is still decreasing. 

![Screenshot from 2022-11-22 12-08-19](https://user-images.githubusercontent.com/45361823/203300568-07036ba6-d2eb-460d-87eb-439aedeb67cb.png)

**Comment by AntonioConsilvio** [comment]
Hi @rozliv, I need an other information. If you run `yarprobotinterface` on icub head from a bash, you should see several errors about HW fault status of joints 4,5,6 and 7 (and others error if there are any). Can you send us a screenshot of all these errors?

Then you have to do the same thing you did before with `FirmwareUpdater`, but after clicking on Discover, you should select the board mc4plus with address 10.0.1.22. 
After that, click on Force ETH Maintenance. Then (always with the board 10.0.1.22) click on Discover. Here we can see if the head can see the skin boards. So send us a screenshot. 

After these steps, restart the boards.

cc @Fabrizio69

**Comment by AntonioConsilvio** [comment]
Hi @rozliv in FirmwareUpdater we can see that the skin boards are not visible. So probably a cable that connects mc4plus to MTB4 ( the skin board) came off.  

Instead regarding joints 5 and 6 maybe they just need a recalibration, the strange thing is for joints 4 and 7 that keep changing value without touching them. 

I think if joint 7 is -2.4 million degrees and still decreasing it probably has a large variation in its value (I don't know why yet). But what is the behavior of joint 4? Does it keep decreasing or does it do other things?

cc @Fabrizio69

**Comment by rozliv** [comment]
Hi @AntonioConsilvio I am enclosing a photo of joint 4 after startup procedure and video of weird joint 4 movements afterwards @matejhof ![Friday startup](https://user-images.githubusercontent.com/45361823/204491744-81fb2112-3545-4a04-91e1-84114e8429a4.jpeg)

https://user-images.githubusercontent.com/45361823/204492114-f870bff5-7e7c-47c2-8543-2c865dfa73d1.MOV

**Comment by AntonioConsilvio** [comment]
Thanks for the video @rozliv , I need to see photos of the AEA sensor of joint 7 too. This is between pinky and ring fingers. I need these views (maybe with flash is better), I colored what I need to see. Because we need to see whether the sensor is well placed or not. 

Front view:
![Front1](https://user-images.githubusercontent.com/114915464/204508627-f334396c-53e3-4648-97fe-3fd7f5ece38e.jpg)

This viewpoint is to see if it is aligned in its seat:

![Alignment1](https://user-images.githubusercontent.com/114915464/204509385-f35d4d22-c530-48e0-be76-96e5d9c4b2f4.jpg)

Last from below:
![Below1](https://user-images.githubusercontent.com/114915464/204509649-a5bbecd2-66de-4738-bb07-4b0a4203e7b1.jpg)

cc @Fabrizio69

**Comment by AntonioConsilvio** [comment]
Whereas regarding joint 4, so if the motor makes this strange movement, on `yarpmotorgui` you should see that the encoder value fluctuates between two values that should be about equal in time (this pair of values does not change), is that correct? 

cc @rozliv @Fabrizio69

**Comment by matejhof** [comment]
I took these two pictures now. Does it help? @AntonioConsilvio 
![IMG_20221129_172701](https://user-images.githubusercontent.com/6461061/204587199-fadb72ec-7ba0-49f8-8ab6-cd35a8c2d9ca.jpg)
![IMG_20221129_172517](https://user-images.githubusercontent.com/6461061/204587223-0e2ba5c0-5c27-496f-8a8e-d1bad884987b.jpg)

**Comment by matejhof** [comment]
Now I started the robot. It came up with all green but joint 4. 
![image](https://user-images.githubusercontent.com/6461061/204592865-d3318534-be3d-4d42-a112-b1d4821fef58.png)

**Comment by AntonioConsilvio** [comment]
This situation is much better than before. But is it just a case or does the robot work better now?
Because if this is the situation maybe it would be enough to recalibrate joint 7 (if the steel tendon is not broken, but it doesn't seem from the photos).

Joints 5 and 6 are in idle because joint 7 is in HW error; if in this situation you press run and then home on joints 5 and 6, they should return to position and run smoothly.

So, how does the robot work now? How in this photo?

cc @Fabrizio69

**Comment by matejhof** [comment]
Thanks @AntonioConsilvio 
I can get to this state by running and homing joints 5 and 6.
![image](https://user-images.githubusercontent.com/6461061/204815120-74fbdffd-168d-4ec6-b85b-e9a7951b6c93.png)
@rozliv  says that joint 4 would get into HW fault only after some time. Yesterday I had this weird oscillations at 30 deg position. This is not happening right now, but something must still be strange there. 
Like yesterday, torso and right hand skin (palm and fingertips) are not responding at all.

**Comment by AntonioConsilvio** [comment]
Hi @matejhof @rozliv, regarding the skins I think there is a disconnected (or almost disconnected) electrical cable so the CPU can't see the skin board (MTB4) on the torso and probably is the same for the other body parts. 

But let's analyze step by step, so now what is your priority, because joint 7 is often less important than others, so it can wait (if you don't need it). 

But joints 4, 5 and 6 give other problems? 

Maybe you can use the robot several times and write in this issue all the times these joints fell HW fault, to figure out how often you have problems with these joints (especially with joint 4) and decide if it is an important problem or if this problem occurs once in ten times. 

If the situation is like [this](https://github.com/robotology/icub-tech-support/issues/1456#issuecomment-1332196941) and joint 4 give no problems, what is your priority? Skins or Joint 7?  

But first we need to understand if joint 4 is really working well or not.

cc @Fabrizio69

**Comment by matejhof** [comment]
We're trying to do some diagnostics here. As for the skin-related connections that could be loose / disconnected, where should we look for them @AntonioConsilvio ?

**Comment by matejhof** [comment]
Hi @AntonioConsilvio, 
we're making progress here. The source of some of the problems was the jumper corresponding to the ring finger. In fact, the finger was hot. 
![IMG_20221201_161454](https://user-images.githubusercontent.com/6461061/205090663-dca68eb1-2895-48be-b8dd-7cad02c8cc6b.jpg)
After we removed the jumper, all joints are working fine. Also the skin of the right hand is fine. When putting the jumper back, we're back to the errors we had before.

What remains dead is the torso skin. In addition, we realized now that also all the skin on the legs is dead (we did not check this before).
cc @0xBEDA @chatom98 @Fabrizio69

**Comment by AntonioConsilvio** [comment]
> Hi @AntonioConsilvio, we're making progress here. The source of some of the problems was the jumper corresponding to the ring finger. In fact, the finger was hot. ![IMG_20221201_161454](https://user-images.githubusercontent.com/6461061/205090663-dca68eb1-2895-48be-b8dd-7cad02c8cc6b.jpg) After we removed the jumper, all joints are working fine. Also the skin of the right hand is fine. When putting the jumper back, we're back to the errors we had before.
> 
> What remains dead is the torso skin. cc @0xBEDA @chatom98 @Fabrizio69

Hi @matejhof @rozliv, when you remove this connector you disconnect the electronic board on fingertip (FTL2).
![image](https://user-images.githubusercontent.com/114915464/205332634-8963b6ee-d653-4e83-84c2-4d0b4d454bc0.png)

So, to understand why it makes this problem, you should check that the cable isn't broken
![Fingertip 2](https://user-images.githubusercontent.com/114915464/205340051-a7358ec7-4f56-49d1-b3d9-3a836027247a.jpg)

And if it is ok, try to remove the nail with this screw
![Fingertip](https://user-images.githubusercontent.com/114915464/205340947-20fd499e-d94d-42ea-83be-ff1c6ce00b9b.jpg)


**!WARNING!** You must be very very delicate, because these cables are so delicate. 

After removing it, you can check the soldering of the cables. Send us a photo of what you can see

cc @Fabrizio69 @maggia80

**Comment by matejhof** [comment]
Thanks! This looks like something for @0xBEDA and @chatom98. We will try next week I guess.

**Comment by AntonioConsilvio** [comment]
Hello @matejhof @rozliv, regarding torso skin, the problem should concern the 4 skin boards (MTB4) placed on torso cover (I circled cables that should have the problem). 
![Logic colored](https://user-images.githubusercontent.com/114915464/205605878-7163c67a-7c86-4a2a-a433-877ce52c09d2.jpg)

To check these problems you should remove torso cover, but these boards are placed like this:
![mt4 placement colored](https://user-images.githubusercontent.com/114915464/205608356-13e5d5a2-7291-465b-9775-d4f4e2ee8b25.jpg)

So you should be able to check the status of the boards from the back and the bottom of the robot at this height, without removing covers:
![board check colored](https://user-images.githubusercontent.com/114915464/205609008-3e988fab-caf1-4f78-8779-06827755a8ad.jpg)

If you have any other questions, write us. 

cc @Fabrizio69

**Comment by matejhof** [comment]
Hi @AntonioConsilvio,
as for the right hand, we solved this problem now. We had a spare ring finger fingertip, so we replaced it and now it works - the jumper is back, joints seems fine, right hand skin is working. thanks to @0xBEDA and @chatom98!

**Comment by matejhof** [comment]
As for the torso ski, what kind of diagnostics should we do? All the 4 boards are blinking in the same way - blue LED is on, red one is blinking. connectors look fine. @AntonioConsilvio ?

**Comment by matejhof** [comment]
Reading from the port can tell us something - the values do not change - they are not live. 
![image](https://user-images.githubusercontent.com/6461061/205915123-56662153-c711-404d-9ba8-2e4f3d830029.png)
If we read from other ports, there are small changes even if noone touches the skin.
On the compensated port, there is nothing going on at all:
![image](https://user-images.githubusercontent.com/6461061/205915642-aa344431-bbd2-4d4d-b212-075bd4b68663.png)
Thanks, @AntonioConsilvio.

**Comment by AntonioConsilvio** [comment]
So the torso skin problem persist.

> Then you have to do the same thing you did before with `FirmwareUpdater`, but after clicking on Discover, you should select the board mc4plus with address 10.0.1.22. After that, click on Force ETH Maintenance. Then (always with the board 10.0.1.22) click on Discover. Here we can see if the head can see the skin boards. So send us a screenshot.
> 
But if boards are blinking, it means that are turn on. So if these boards are on, you should be able to see them on `FirmwareUpdater` by following these steps previously listed.

But when you did that, you don't see them, how we can see in this comment below:






> Hi @AntonioConsilvio, Here are the terminal output as txt file and the screenshot of FirmwareUpdater.
> 
> [output.log](https://github.com/robotology/icub-tech-support/files/10069278/output.log) [cleaned version](https://github.com/robotology/icub-tech-support/files/10069407/new.log)
> 
> ![Screenshot from 2022-11-22 17-23-22](https://user-images.githubusercontent.com/45361823/203368987-f900b6a8-d0ef-4005-9bab-cd6f149b7252.png)


So maybe retry to follow those steps and check if skin boards (MTB4) are visible on `FirmwareUpdater`. 

cc @Fabrizio69

**Comment by rozliv** [comment]
Hi @AntonioConsilvio,
the boards are not visible on FirmwareUpdater:
`FirmwareUpdaterCore::getCanBoardsFromEth(): No CAN boards found beneath  "10.0.1.22"  after a successful driver init.`


Errors from yarplogger: 
`	1320.548923	ERROR			 from BOARD 10.0.1.22 (face-eb22-j0), src CAN1, adr 0, time 1478s 642m 123u: (code 0x00000019, par16 0x0901 par64 0x0000000000000000) -> SYS: EOtheCANservice could not tx frames on CAN bus. In par16 there is: on msb the size of txfifo, on lsb a code. + .
`

@matejhof @0xBEDA

**Comment by AntonioConsilvio** [comment]
Hi @rozliv @matejhof, I think  the problem is the cable **W_N9** (Orange), which connects mc4plus (EB22, Blue) to the first MTB4 (9B7, Green) of the torso: 


![Image](https://user-images.githubusercontent.com/114915464/207630868-a1c2b23d-10b0-4f92-b9b1-b589c333f78d.jpg)



![Image](https://user-images.githubusercontent.com/114915464/207630887-3a1f3d7c-7b21-4709-84f8-d8c22878be4f.jpg)



So, you should be able to check the connector on MTB4 (green) from the bottom of the torso: 


![Image](https://user-images.githubusercontent.com/114915464/207631314-20299663-a10a-475d-9a80-23715c79d7f7.jpg)

If the connector on MTB4 is fine, the problem should be the connector on mc4plus (blue), which should be the first of the three boards inside the head, as you can see in the photo below:



![Image](https://user-images.githubusercontent.com/114915464/207632641-bb49737a-e186-4a82-9e27-d75b06384405.jpg)


If you have to open the head to check the connector on mc4plus, to figure out where the cable is, there are colored cubes on the cables, check these cubes and find the cable with this name: **W_N9**.


Write to us if you have any questions.

cc @Fabrizio69

**Comment by rozliv** [comment]
Hi @AntonioConsilvio, 
just checking the cable and connector on mc4plus made it work. Thank you!


@matejhof
