### ISSUE TITLE
Mechanical backlash on the neck yaw joint

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1472]
### Device name 🤖

iCubGenova09

### Request/Failure description

There is some mechanical backlash on the neck yaw. See attached video

### Detailed context

https://user-images.githubusercontent.com/18591940/204561146-a9e35551-14d0-496e-a1b3-19393c481cc5.mp4

**Comment by GiacomoVassallo13** [comment]
Hi. The backlash on the yaw joint of the neck has been solved. The game was due to various factors: 
The threads of the head fixing holes were badly damaged and have been rethreaded.
The gear set screws were loose, they were tightened and glued.

In addition, the correct fixing of the grains of the wave generator on the shaft was verified.
@AntonioConsilvio told me that the robot has been tested and the neck problem hasn't reappeared.

cc: @Fabrizio69 @AntonioConsilvio @S-Dafarra

**Comment by S-Dafarra** [comment]
Here is how it is right now:

https://user-images.githubusercontent.com/18591940/207357977-b8fa7161-da6e-404b-b059-3dff28adfbfe.mp4

It is definitely better, even if I am not sure how much backlash there is in a nominal condition

**Comment by S-Dafarra** [comment]
Kinda related, the sleeve of the cables leaving the head seems shredded by the motor pulley
![image](https://user-images.githubusercontent.com/18591940/207387682-a04405de-f4c6-4f14-90fe-c903838f4511.png)

**Comment by GiulioRomualdi** [comment]
To complement the issue I add a video showing what happens when the neck is in position control

https://user-images.githubusercontent.com/16744101/207408452-a0aa0f81-0eb1-4459-b36e-dd5b1d7b7d2e.mp4


here the joints in the motorgui
![20221213_182800](https://user-images.githubusercontent.com/16744101/207408495-c4b0a4da-33d8-4649-a487-9f9ab65696ff.jpg)

**Comment by GiacomoVassallo13** [comment]
Hi, the neck motors have been tested in control to verify that the backlashs are solved. The joints move correctly the recoil on the joints no longer occurred . The problems have been fixed.

cc: @Fabrizio69 @AntonioConsilvio @maggia80

**Comment by AntonioConsilvio** [comment]
Here you can see the result of the intervention

https://user-images.githubusercontent.com/114915464/208656930-7c3ed0c1-4712-45b6-9239-4a0b68197273.mp4



https://user-images.githubusercontent.com/114915464/208656939-7e488002-0e1a-42cd-b65b-3e1a16cb84b4.mp4

cc @GiacomoVassallo13 @maggia80 @GiulioRomualdi @S-Dafarra @Fabrizio69
