### ISSUE TITLE
Left thumb distal often does not calibrate

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1479]
### Device name 🤖

iCubGenova09

### Request/Failure description

The left thumb distal joint often does not calibrate and remains not configured, although the joint encoder seems to measure the angle corrrectly.

### Detailed context

@AntonioConsilvio tried to move the joint by hand and it seems to give more resistance compared to the right. After moving it by hand a bit, it calibrated again, but it might be worth checking before it breaks.

**Comment by AntonioConsilvio** [comment]
Hi @S-Dafarra, before moving the joint, the cable was in a bad position. After solving this problem, the distal thumb no longer failed calibration. Also, I tried several times with 'yarpmotorgui' and it works without any problems. 

The motor resisted because there is no longer a seat for the screwdriver. 

However, now the joint seems to be working, if the problem occurs again you can reopen the issue.

cc @Fabrizio69
