### ISSUE TITLE
iCubGenova11 - r_elbow MotorPos is always 0

### ISSUE THREAD

**Issue by fedeceola** [robotology/icub-tech-support#1481]
### Device name 🤖

iCubGenova11

### Request/Failure description

As per title, r_elbow MotorPos is always 0.

### Detailed context

After the work done to fix the problems in #1476, @AntonioConsilvio, mentioned that the `MotorPos` value of the `r_elbow` is always 0.
![image](https://user-images.githubusercontent.com/32268209/209140759-8a1ba7f1-65c4-44e1-b65e-f26f02df28c0.png)
Due to this, when running the `yarprobotinterface`, the `r_elbow` and the right shoulder joints are in idle.
![image](https://user-images.githubusercontent.com/32268209/209141396-3575dc26-ab0e-4995-9a5e-fcf66145a79a.png)
To solve this problem, it's necessary moving to the home configuration in the `yarpmotorgui` all the right arm joints.
![image](https://user-images.githubusercontent.com/32268209/209141688-3e17c7a7-0e6f-48ea-9041-8ce07fd9b1b3.png)
cc @xEnVrE

**Comment by AntonioConsilvio** [comment]
Hi @fedeceola @xEnVrE , I understood that the idle problem is caused by another small thing that has been solved. 

Anyway, the MotorPosition is always read at 0, but this does not create real problems because the Encoder information is enough to move the joint, and the MotoroPosition is not needed. 

Maintenance work might be invasive, but, for now, not necessary since it is possible to use the robot without problems. If one day, for some reason, you need the MotorPosition of this joint, you can reopen this issue and we can try to solve the problem.

cc @maggia80 @Fabrizio69
