### ISSUE TITLE
iCubGenova11 - Left thumb distal deviates when the opposition goes towards 90 degrees

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-tech-support#1482]
### Device name 🤖

iCubGenova11

### Request/Failure description

The left thumb distal deviates when the opposition goes towards 90 degrees. A picture of the problem follows:

![image](https://user-images.githubusercontent.com/6014499/209301591-48391890-c04b-44bb-83e3-36934041690f.png)

### How does it affect you?

It is not possible to command the thumb opposition and distal joints independently.

**Comment by xEnVrE** [comment]
cc @fedeceola

**Comment by AntonioConsilvio** [comment]
Hi @xEnVrE @fedeceola, this problem was caused by the sheath of the steel cable that was outside. Now the thumb can reach 90 degrees without that distal being pulled. 

Also, I recalibrate thumb oppose of left arm, so now both thumb oppose are in the same position when are in the same degrees.


If these problems occur again, you can reopen this issue.

cc @maggia80 @Fabrizio69

**Comment by xEnVrE** [comment]
Thanks @AntonioConsilvio
