### ISSUE TITLE
iCubGenova11 - Problem with r_pinky.

### ISSUE THREAD

**Issue by fedeceola** [robotology/icub-tech-support#1492]
### Device name 🤖

iCubGenova11

### Request/Failure description

When closing the `r_pinky` joint the ring and the little don't close synchronously differently from the left hand.

cc @xEnVrE 

### Detailed context

-

**Comment by AntonioConsilvio** [comment]
Hi @fedeceola @xEnVrE, the problem was detected in this pulley on the ring of the left hand:
![Ring](https://user-images.githubusercontent.com/114915464/215475110-d07ec39a-94eb-483f-8961-3f44e3c1a88b.png)

The cable does not run around the pulley as it should. 

We have arranged with @Nicogene (who has to use the robot tomorrow), and @GiacomoVassallo13 and I will do the intervention tomorrow morning (around 9:30 am).

**Comment by AntonioConsilvio** [comment]
Hi @fedeceola @xEnVrE, @GiacomoVassallo13 fixed this problem. Now the cable go around the pulley without problems.

![Image](https://user-images.githubusercontent.com/114915464/216085382-ebd9ac77-4db8-4044-bcea-e877cf2c91cb.png)


The problem regarding synchronized closing however persists, but in reverse. Whereas before the ring finger closed earlier than the little finger, now the little finger closes slightly earlier than the ring finger. 
To fix this problem, it is necessary to rewire the ring finger and little finger, however since the wiring process is quite sloppy, it is not guaranteed to fix the problem. It may fix the problem, or it may not. 

So, counting that rewiring requires opening the hand and forearm, do you want to try it anyway or not?

cc @sgiraz

**Comment by xEnVrE** [comment]
Thanks for the fix @AntonioConsilvio @GiacomoVassallo13 

Regarding the more invasive maintenance, we will discuss tomorrow and let you know!

**Comment by AntonioConsilvio** [comment]
Hi @xEnVrE @fedeceola, maintenance is not needed for now, so I am closing this issue.
However, if you find this maintenance necessary in the coming days, you can reopen this issue or open a new one.

cc @sgiraz
