### ISSUE TITLE
Build jumper cables to bypass ethernet connections when removing forearms

### ISSUE THREAD

**Issue by HosameldinMohamed** [robotology/icub-tech-support#1506]
### Device name 🤖

iCubGenova09

### Request/Failure description

We removed the forearms in #1504 to perform a test for iRonCub. We need to have an ethernet cable to bypass the forearms for completing the ethernet loop.

The connectors are of different types so we need small jumper cables to have compatibility with the connectors.

### Detailed context

See https://github.com/robotology/icub-tech-support/issues/1504#issuecomment-1433484053

## Right arm

![right](https://user-images.githubusercontent.com/45564317/219451439-1186b3b9-f4bf-43a7-b56f-0dba34b055fb.png)

## Left arm

![left](https://user-images.githubusercontent.com/45564317/219451491-6f3d6621-7e8c-4a74-afe3-fa264c19b369.png)

**Comment by AntonioConsilvio** [comment]
Hi @HosameldinMohamed, I changed this connector (6 pins)


![Image](https://user-images.githubusercontent.com/114915464/220084218-873dedbb-1aba-4401-a53c-f38260b0a666.png)

With a new one (5 pins):




![Image](https://user-images.githubusercontent.com/114915464/220084382-0c29d174-c767-49ad-9dd0-466c21fccd12.png)

So you can connect it on the board, and also on the male connector of the fore arm:



![Image](https://user-images.githubusercontent.com/114915464/220084518-e7f79d59-8214-4e68-8cd3-146613c55f3c.png)


If you have to connect the cable with the male connector of the fore arm, be careful because one PIN is empty and you have to be sure that you are connecting pin to pin.


When you have tested the robot, give us feedback.

cc @sgiraz

**Comment by HosameldinMohamed** [comment]
Hi @AntonioConsilvio 
We tested the robot.. it can start with no issues!

Thanks!
