### ISSUE TITLE
what is the recommanded default gesture of icub when not in use

### ISSUE THREAD

**Issue by jimingda** [robotology/icub-tech-support#1576]
### Device name 🤖

iCubShanghai01

### Request/Failure description

As default, if properly exit the application in yarpmanager,  the head and torso of icub are tilted, as the gesture in the pic below rather than upright, is it the recommand situation？

### Detailed context

![D9267F3B-B283-4945-BA27-6A00F0434BC1](https://github.com/robotology/icub-tech-support/assets/7019692/82abf353-5378-436a-9c31-8f466fcf44f5)

**Comment by jimingda** [comment]
The reason we have this question is that it doesn't looks normal, but maybe this tilted situation is good for icub, can reduce the tension on the cable driven, and extend its service life.

**Comment by AntonioConsilvio** [comment]
Hi @jimingda, the position the robot assumes once the yarprobotinterface is closed is completely normal. 

If in the first period the robot's neck remained straight instead of falling, it was simply due to the friction produced by the gearbox.

After a bit of running in, the gearbox produces less friction, so it's actually a positive situation.

So, there are no problems about it!

cc @sgiraz

**Comment by sgiraz** [comment]
Hi @jimingda,

The answer provided by @AntonioConsilvio should have clarified your doubts, so I am going to close this issue. Feel free to reopen it if necessary.
