### ISSUE TITLE
ergoCubSN000 right thumb OC gets stuck

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1580]
### Device name 🤖

ergoCub S/N000

### Request/Failure description

We noticed that at a certain point, the right thumb stopped following commands.

### Detailed context

The joint appears to be in position mode, but it does not follow the commands and the motor position is stuck to a given value.

**Comment by sgiraz** [comment]
Hi @AntonioConsilvio,

May the issue reported here correlated to the #1578 ?

**Comment by AntonioConsilvio** [comment]
Hi @sgiraz the problem is unrelated. 

However, the problem was that the MotorPosition of the Thumb OpenClose reached the value of [rotoPosMax](https://github.com/robotology/robots-configuration/blob/d106aacf66104e14fc93a14a3e17e0311fdd6b12/ergoCubSN000/hardware/mechanicals/right_arm-eb22-j7_10-mec.xml#L30).

During the demo we changed this value from -6500 to -100, but the robot needs someone to hold the finger open during calibration to calibrate correctly.

This problem is probably due to too long a tendon, so we will organise an intervention to solve it.

cc @maggia80 @S-Dafarra

**Comment by S-Dafarra** [comment]
cc @marcellosavoldi

**Comment by sgiraz** [comment]
A PRs is coming to fix this issue:
- https://github.com/robotology/icub-firmware-build/pull/95

**Comment by AntonioConsilvio** [comment]
Hi @S-Dafarra @MSECode, me and @fbiggi tightened the thumb tendon open close and it seems to behave better.

https://github.com/robotology/icub-tech-support/assets/114915464/8125c8bf-fcf9-41fd-9779-b162aaf77287

The abundance of the tendon has been eliminated as much as possible.

cc @sgiraz
