### ISSUE TITLE
iCubGenova04 (iRonCub1) S/N:031: problem with right leg ankle board

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1591]
### Device name 🤖

iRonCub1 - iCubGenova04

### Request/Failure description

The robot does not start, in the yarprobotinterface there is this error:

```
[ERROR]  from BOARD 10.0.1.9 (right_leg-eb9-j4_5), src LOCAL, adr 0, time 253s 946m 428u: (code 0x00000013, par16 0x0001 par64 0x0000000000000000) -> SYS: the EOtheInfoDispatcher could not accept a eOmn_info_properties_t item inside its transmitting queue. In par16 there is the number of lost items. + .
```

### Detailed context

we run firmwareupdater and we don't see the right foot FT sensor when we run `discover`.

cc @antonellopaolino

**Comment by sgiraz** [comment]
Maybe we have to change the ems eb9 board because the power is 2.7V instead of 5V.\
We'll take a look at it asap.

**Comment by gabrielenava** [comment]
keeping it open: the problem still persists. It would be nice to fix this and https://github.com/robotology/icub-tech-support/issues/1666 so that we can collect more data for the wind tunnel paper activity with @antonellopaolino

**Comment by pattacini** [comment]
To prevent the automation from marking issues as https://github.com/robotology/icub-tech-support/labels/stale it suffices to use the label https://github.com/robotology/icub-tech-support/labels/pinned.

**Comment by AntonioAzocar** [comment]
Hi!
Checking the output voltage from the CAN connector of the EMS4 to which the **9N2** cable is connected, we noted that it wasn't giving the required **5V**, but only **2** and obviously this voltage wasn't enough to power the FT sensor on the right foot.
So, in order to avoid changing the board directly, we took the power supply from the P8 connector and by doing this, the problem was solved and the robot works correctly.

![5v_ems_strain2](https://github.com/user-attachments/assets/a19ec276-7398-412b-89d3-7eea45974b6b)

![5v_ems_strain2_FirmwareUpdater](https://github.com/user-attachments/assets/d7139f92-0280-4772-8854-98617319c5a1)


cc @AntonioConsilvio

**Comment by gabrielenava** [comment]
thank you @AntonioConsilvio and @AntonioAzocar! it seems working fine now!

**Comment by AntonioConsilvio** [comment]
Well! Good job @AntonioAzocar. Closing! 🚀
