### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Two cables disconnected from the connector during calibration and knee encoder does not work

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-tech-support#1654]
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

Two electronic cables disconnected again during the calibration. One is the same cable of yesterday, (right leg knee), while the other is the right leg ankle pitch motor.

### Detailed context

cc @davidegorbani @DanielePucci

**Comment by AntonioAzocar** [comment]
I fixed the RLS3 cable of the right leg knee and the RLS4 cable of the right ankle pitch.
There are still problems with the AMO of the right knee, but it shouldn't be a wiring problem. So, today we'll continue to work on it


RLS3

![MicrosoftTeams-image (9)](https://github.com/robotology/icub-tech-support/assets/130973726/f2d8df49-a08d-40a8-90d0-2e58e4a54c41)


RLS4

![MicrosoftTeams-image (12)](https://github.com/robotology/icub-tech-support/assets/130973726/f554b2e9-0daf-4ef3-86d6-03c2339ff5a6)


cc @gabrielenava

**Comment by gabrielenava** [comment]
thank you @AntonioAzocar I have updated the title of the issue in view of the problem that emerged with the knee encoder after fixing the cable!

**Comment by DanielePucci** [comment]
Also here I would add glue to the connector @AntonioConsilvio @sgiraz

**Comment by AntonioConsilvio** [comment]
Hi @gabrielenava, the right knee joint continued to fail because of the EMS board to which it was connected (EB12).

In fact the channel to which the AMO was connected stopped working (Connector P7), fortunately the EMS board had other free SPI channels to which it is possible to connect the AMO.

In fact, I connected the AMO board to Connector P11.

The robot has been tested and it is working properly now!

cc @sgiraz @HosameldinMohamed
