### ISSUE TITLE
ergoCub 1.0 S/N:000 – Neck tendon broken while running the robot interface on the pole

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1657]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

We run the robot interface on the pole and one cable of the neck got broken.

### Detailed context

This is probably due to the fact that the neck calibrates after the torso and the neck got whiplash

**Comment by GiulioRomualdi** [comment]
cc @isorrentino

**Comment by SimoneMic** [comment]
![20231013_153922](https://github.com/robotology/icub-tech-support/assets/86918431/59e50675-ff27-4af3-89b6-3a2444d37137)
I've also noticed that the belt in the picture is misaligned and damaged

**Comment by GiacomoVassallo13** [comment]
Hi. the damnaged cable hase been replaced wich a new one. The old cable was most damnaged bacause the tendon it slipped into the space between the pulley and the bearing. The belt it' s okay. It is misaligned and worn because the belt is cut during the assembly phase.

cc: @sgiraz @Fabrizio69 @AntonioConsilvio

**Comment by sgiraz** [comment]
Well done @GiacomoVassallo13! 

Closing as solved!
