### ISSUE TITLE
ergoCub 1.0 S/N:000 – Right wrist reaches the limit while calibrating and it remains there

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1683]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

While walking, the right wrist reached its limits unexpectedly, without being controlled by the walking controller. We attempted to reboot the robot and the motors several times, but when the YARP robot interface started, the motor exceeded the limits 

### Detailed context

To prevent damaging the motors, we immediately switched off the robot.

### Additional context

Here are images of the robot after executing the YARP robot interface, revealing the asymmetry.

![MicrosoftTeams-image (5)](https://github.com/robotology/icub-tech-support/assets/16744101/0b53dd74-2706-40cd-8360-ff5a87e913cf)
![MicrosoftTeams-image (4)](https://github.com/robotology/icub-tech-support/assets/16744101/85ef10a1-7bff-428e-b9f3-7f89c78a9107)

### How does it affect you?

There's a demo scheduled in the upcoming days (https://github.com/ami-iit/lab-events-demos/issues/281). Additionally, it's worth noting that the robot will be departing from IIT permanently (https://github.com/ami-iit/lab-events-demos/issues/284).

cc @S-Dafarra @DanielePucci @carloscp3009 @paolo-viceconte

**Comment by S-Dafarra** [comment]
I have checked the ``yarpmotorgui`` and all the wrist joints remain constantly equal to zero even when moving the joint by hand. I also started the robot with [these two parameters](https://github.com/robotology/robots-configuration/blob/003ffaa1de00901e0afee9767e4d110c633f0a57/ergoCubSN000/general.xml#L7-L8) to true and this is the output

![image](https://github.com/robotology/icub-tech-support/assets/18591940/b73ac01a-c734-402b-881b-7af806e47bee)


When moving the joints by hand, the motor encoder change, but not the joint ones.

cc @Fabrizio69 @Gandoo

**Comment by sgiraz** [comment]
>I also started the robot with [these two parameters](https://github.com/robotology/robots-configuration/blob/003ffaa1de00901e0afee9767e4d110c633f0a57/ergoCubSN000/general.xml#L7-L8) to true and this is the output

Hi @S-Dafarra which version of FW of AMC is currently flashed on the robot?

>I have checked the yarpmotorgui and all the wrist joints remain constantly equal to zero even when moving the joint by hand.

Probably we have to check the wires/connector of the AEA2 encoder of the wrist.

**Comment by S-Dafarra** [comment]
> > I also started the robot with [these two parameters](https://github.com/robotology/robots-configuration/blob/003ffaa1de00901e0afee9767e4d110c633f0a57/ergoCubSN000/general.xml#L7-L8) to true and this is the output
> 
> Hi @S-Dafarra which version of FW of AMC is currently flashed on the robot?

101.8

Indeed, there is a mismatch between the two wrists

![image](https://github.com/robotology/icub-tech-support/assets/18591940/3ff8b768-fd66-4a11-9a0f-93ba2ce195e4)

**Comment by sgiraz** [comment]
> Indeed, there is a mismatch between the two wrists

In this case, it is normal, since it is an old FW version compared to the latest one.

### 2 possible solutions:

1. #### A "quick" swap test:
It consists of swapping the 2 AMC boards with the aim of proofing whether there is a faulty board or not. To do this test you need the same binaries currently flashed on the robot (usually within the `icub-firmware-build` folder on the robot). Swap physically the 2 boards and flash the `amc.wrist.left.hex` binary to the board mounted on the left arm and the amc.wrist.right.hex mounted to the right one.
If the problem is swapped from the right wrist to the left, it means that the board has to be replaced.


2. #### Flash the [latest FW version of the `amc`][1]
In this case, there exists only one binary called `amc.hex` to flash on both amc boards. In order to use this FW you have to perform some minor changes to the configuration files of both left and right arms:

in `ergoCubSN000\hardware\mechanicals\right_arm-eb30-j4_6-mec.xml` replace the `JOINTSET_CFG` group with the following:
```xml
    <group name="JOINTSET_CFG">
        <param name= "numberofsets"> 1 </param>
        <group name="JOINTSET_0">
            <param name="listofjoints">  0 1 2         </param>
            <param name="constraint">    ergocubwrist  </param> <!-- none for calibration -->
            <param name="param1">        20            </param>
            <param name="param2">        1             </param>
        </group>
    </group>
```

in `ergoCubSN000\hardware\mechanicals\left_arm-eb31-j4_6-mec.xml` replace the `JOINTSET_CFG` group with the following:
```xml
    <group name="JOINTSET_CFG">
        <param name= "numberofsets"> 1 </param>
        <group name="JOINTSET_0">
            <param name="listofjoints">  0 1 2         </param>
            <param name="constraint">    ergocubwrist  </param> <!-- none for calibration -->
            <param name="param1">        20            </param>
            <param name="param2">        0             </param>
        </group>
    </group>
```

>**Warning**
> The solution nr.2 hasn't been tested yet on ergoCub1.0 S/N:000, but only on the wrists of ergoCub1.1 S/N:001. It should be fine with the configuration posted above, but please pay attention.

cc @valegagge @marcoaccame @Nicogene 

  


[1]: https://github.com/robotology/icub-firmware-build/tree/devel/ETH/AMC

**Comment by sgiraz** [comment]
During an F2F call with @S-Dafarra I got that the wrist was working correctly while it was walking. Then at a certain point, the wrist went out of control. In this case, it shouldn't be a FW's version problem. It is more probable that it is a HW problem since the jogger reads the AEA2 values correctly.

**Comment by sgiraz** [comment]
After detaching and re-attaching the `amc` of the right arm (without changing any FW version), something seems improved. Another indicator that it may be a mechanical or electrical issue.

**Comment by sgiraz** [comment]
The wrist is now under repair since one of the belts is broken:

![image](https://github.com/robotology/icub-tech-support/assets/18039045/508d7693-903b-46da-9459-d4dad65b9ba3)

cc @S-Dafarra @GiulioRomualdi @fbiggi @fiorisi @GiacomoVassallo13

**Comment by S-Dafarra** [comment]
@maggia80 also spotted a damaged wrist encoder connector. This might have been the source cause of this issue, although the breakage of the belt might have been caused by continuous wear.
