### ISSUE TITLE
ergoCub 1.1 S/N:001 – r_index_oc does not move

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1713]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The right index open close stopped moving while teleoperation

### Detailed context

According to the motorgui the joint seems fine still the motor position is -26817.3 deg

### How does it affect you?

Tomorrow afternoon we have a demo and it would be nice to have it functional https://github.com/ami-iit/lab-events-demos/issues/293

**Comment by AntonioConsilvio** [comment]
Hi @GiulioRomualdi. the problem occurred because the pin-screws that hold the pulley attached to the pinky motor were unscrewed. So the motor was running without making the finger move.

I fixed this problem by re-tightening the pin-screws.

We are planning a redesign to prevent it from happening again.

cc @maggia80 @fbiggi @salvi-mattia @Fabrizio69
