### ISSUE TITLE
ergoCub 1.1 S/N:001 – Right hip roll does not calibrate

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1754]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

Similar to https://github.com/robotology/icub-tech-support/issues/1753 we tried to switch on the robot and the right hip roll do not calibrate.

### Detailed context

The joint do not move at all and it remains in idle mode 

![image](https://github.com/robotology/icub-tech-support/assets/16744101/dc710e77-b507-4798-b597-40c3f0184508)

The encoders move if the joint is manually moved.

After calibration the robot appears like the following picture

![MicrosoftTeams-image(7)](https://github.com/robotology/icub-tech-support/assets/16744101/7c7a72d0-6f2b-4a56-9bb3-9b51ef2b9674)

### Additional context

Here the logger 
[log_ergocub-torso_yarprobotinterface_1440_right_hip_roll_failed.txt](https://github.com/robotology/icub-tech-support/files/14362045/log_ergocub-torso_yarprobotinterface_1440_right_hip_roll_failed.txt)

**Comment by GiulioRomualdi** [comment]
We tried to increase the maximum PWM in the hip roll from 8000 to 12000 still it is not starting

**Comment by AntonioConsilvio** [comment]
Hi! The joint didn't calibrate because the optical disk was stained due to the motor burn:

![IMG_20240223_111845](https://github.com/robotology/icub-tech-support/assets/114915464/b8e3a6bd-57a9-4ec5-918c-d07821625986)

![IMG_20240223_112500](https://github.com/robotology/icub-tech-support/assets/114915464/72527d9d-cb7b-4c8e-b1a0-bd41e89b422a)

We will replace the optical disk, but We will not replace the motor, as although it has warmed up and has burnt areas, the phases have a resistance of 1.0 between red-black and white-black, and 1.1 between white-red, so they should be acceptable for the operation of the joint.

However, we do not know how long the joint could sustain prolonged use.

With @MSECode we will work on enabling the temperature reading.

cc @Fabrizio69 @fbiggi

**Comment by AntonioConsilvio** [comment]
Hi @GiulioRomualdi, we mounted the rotor, calibrated and tested the joint. seems to be working correctly now.

However, during testing we detected a malfunction on the left hip roll.

We discovered that the motor was burnt out, so we proceeded with the replacement.

We have now tested the robot and both joints work correctly.

Here is the PR for the new joint calibrations:

- https://github.com/robotology/robots-configuration/pull/620

Please give us feedback as soon as possible, thank you!

cc @S-Dafarra

**Comment by S-Dafarra** [comment]
The robot is able to walk. I noticed some more shaking, but they did not interfere too much. Also, I tested with the parameters we used in Bruxelles, which are more conservative than usual.

**Comment by sgiraz** [comment]
Thank you for your feedback @S-Dafarra.

Closing!
