### ISSUE TITLE
ergoCub 1.0 S/N:001 – Tendon broken for right index add

### ISSUE THREAD

**Issue by PasMarra** [robotology/icub-tech-support#1775]
### Robot Name 🤖

ergoCub 1.0 S/N:001

### Request/Failure description

When giving a setpoint through the motorgui, the finger doesn't move and you can here this noise coming from the motor. We suspect that the tendon is broken. See video below.

### Detailed context

https://github.com/robotology/icub-tech-support/assets/143645988/02391cd6-57a5-4dcf-82ac-a39a50c3b8d1

**Comment by AntonioConsilvio** [comment]
Hi @PasMarra! As a result of the mechanical upgrades of the lowerarms performed by @fbiggi, the index adduction have started working again, see video:


https://github.com/robotology/icub-tech-support/assets/114915464/1b8cf042-8708-42a4-888d-313b86cefed2

Here the PR that enable the joint calibration:

- https://github.com/robotology/robots-configuration/pull/653

Since the robot has already been tested, I will proceed with closing the issue. If there are any other problems, feel free to open a new issue!

> [!Note]
> Just for information, the adduction has not tendons, but a series of linkages connected to a little motor. The problem was caused by the linkages being physically disconnected from the motor shaft.
