### ISSUE TITLE
ergoCub 1.1 S/N:001 – The robot doesn't switch to battery mode

### ISSUE THREAD

**Issue by SimoneMic** [robotology/icub-tech-support#1816]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

After pressing the battery switch in the robot torso nothing happens.
The battery status is not displayed on the robot monitor on the back

### Detailed context

This is the only error displayed on the YRI
```
[ERROR] from BOARD 10.0.1.2 (left_arm-eb2-j0_1) time=9396s 46m 605u : SYS: a service has detected that some CAN boards are still not transmitting. Type of service category is eomn_serv_category_battery. Lost CAN boards are on (can1map, can2map) = ([  ] , [ 2 ]). Total disappearance time: 20001 [ms]

```

**Comment by AntonioConsilvio** [comment]
Hi @SimoneMic, I investigated the problem yesterday. 

Probably, the battery was accidentally forgotten switched on over the weekend which caused the battery to discharge completely.

The BMS (the battery control board) sent the battery into `undervoltage` protection and so to restore the battery functioning, I connected the charger directly to the battery in order to charge it to the minimum amount needed to overcome the `undervoltage` threshold.

Now the battery is charged and working properly. Closign!

cc @S-Dafarra
