### ISSUE TITLE
iCubShanghai01 S/N:049 – The CPU Button Automatically Shuts Down After Being Pressed to Green for 60 Seconds

### ISSUE THREAD

**Issue by jimingda** [robotology/icub-tech-support#1826]
### Robot Name 🤖

iCubShanghai01 S/N:049

### Request/Failure description

When I press the CPU button, it turns green. However, after approximately 60 seconds, it turns red and shuts down automatically.

### Detailed context

The phenomenon is demonstrated in the attached video [here](https://drive.google.com/file/d/1a8RcFvz4X6j8Dj9X0N69B0E7vycWK_27/view).

### Additional context

N/A

### How does it affect you?

The iCub can't be turned on.

**Comment by jimingda** [comment]
Hi,

Anyone can have a look at this issue?

Appreciate in advance.

**Comment by AntonioConsilvio** [comment]
Hello @jimingda! Sorry for the late reply.

Before you can solve the problem, you have to find out the cause.

So as a first test, we suggest removing the head cover and disconnecting the CPU power connectors (this should be done with the robot switched off).

To remove the cover, unscrew the two side screws:

![head1](https://github.com/robotology/icub-tech-support/assets/114915464/8a38d754-e5b5-4bf6-b24e-c9673e501a77)
(The other screw is on the other side of the head)

Removing the cover will expose the power cables:

![IMG_20240701_112521](https://github.com/robotology/icub-tech-support/assets/114915464/47e20976-c7db-4627-a714-8cf1e401c5c7)

Disconnect them and then try switching on the CPU and see how it behaves!

Please, send us feedback and if you have any questions feel free to ask!

**Comment by jimingda** [comment]
Thank you @AntonioConsilvio 

I removed the cover but couldn't find the white connector as shown in your picture. Below is a photo I took of the inside of the iCubShanghai's head.

![60eb39c57l78586825ff2a0651ea4a7d](https://github.com/robotology/icub-tech-support/assets/7019692/db8d11ab-5a95-44ac-8658-521a76fdf7e1)
![18934cdd4naf818ea64be08261cc1da2](https://github.com/robotology/icub-tech-support/assets/7019692/3bc98321-e4d7-4f4a-87ab-fcedb463358d)

**Comment by AntonioConsilvio** [comment]
Hi @jimingda , you can safely remove the back cover of the head for better visibility (it should not be held with screws, just pull it).

After that, the connectors should be there, try pulling the yellow and black cables out of the head and see if they come out!

Feel free to leave me feedback afterwards!

**Comment by AntonioConsilvio** [comment]
Hi @jimingda, I don't think the connectors are in the sheath connecting the back to the head.

I think they might be in the head. For example under the plate (red circle in the picture below), so try pulling the yellow and black cables out by, for example, taking them from the green circle and pulling them outwards.

![1](https://github.com/robotology/icub-tech-support/assets/114915464/18b2ad46-2d41-4b4e-954c-47d912f7ddaa)

**Comment by jimingda** [comment]
Hi @AntonioConsilvio 

I found two connectors, one connects 2 cables another connects 3 cables, and it seems difficult to get it out.
 
![182873584pd5bd75d7a0f8eb817b2f1e](https://github.com/robotology/icub-tech-support/assets/7019692/41f42bb5-5e31-48aa-9c21-7d44529c1d7e)
![bd1df1fcbmc179989ec4ddfa59aa197a](https://github.com/robotology/icub-tech-support/assets/7019692/29d41d35-daf2-48dd-a6b6-9332b6758e2b)

**Comment by AntonioConsilvio** [comment]
hi @jimingda, as shown in this [picture](https://github.com/robotology/icub-tech-support/issues/1826#issuecomment-2202681290), you can try pulling the cables from the green circle and see if the connectors come out.

If they do not come out, you can try unscrewing four screws and removing the top plate, so that the connectors are exposed and more visible.

Two screws are the ones circled in red in the photo below, the other two are on the other side of the head. (obviously with the robot switched off)

![headdd](https://github.com/robotology/icub-tech-support/assets/114915464/974cf7ca-115d-4b80-93b5-19423b86dd23)

**Comment by jimingda** [comment]
Hi @AntonioConsilvio 

I can pull the cables from the green circle, and disconnect the connector.
![3d28e9953o1151a9ac2df29d75006426](https://github.com/robotology/icub-tech-support/assets/7019692/daf7e6d1-34a4-44eb-b44e-5739b5a2555f)

**Comment by AntonioConsilvio** [comment]
Great @jimingda!

We now have 3 possible causes:

- The CPU
- The RFE board
- The face expressions

To figure out the cause, I would suggest you follow the steps below:

- Reconnect the connector and start the robot and see if the problem recurs.

- If it recurs, try disconnecting the power supply (yellow and black cable) of the board you see circled in red in the photo below (board name: `RFE`):
(you can see the cables in the photo and I have circled them in blue).

![rfe](https://github.com/robotology/icub-tech-support/assets/114915464/c4c83c98-2504-4abf-ab78-f5fe4c0460e2)

At this point only the CPU remains connected to the power supply, while the `RFE` and face expressions are disconnected.

Try switching the robot on and see how it behaves!

**Comment by jimingda** [comment]
Hi @AntonioConsilvio 

Any advices on `when I pressed the Motor button, it did not turn green, and the CPU button shut down automatically as well.` ?

Thanks.

**Comment by AntonioConsilvio** [comment]
Hi @jimingda, close to the power connector you disconnected (2 PINs), there should be another one (3 PINs). 
You can also see it in the photo you sent:

![3pin](https://github.com/robotology/icub-tech-support/assets/114915464/973bb851-eac3-4db7-b63c-32ee3e2e9c01)

I would try unplugging it, so you will have disconnected the head boards that are turned on when you turn on the motors.

At this point I would advise you to switch on the CPU and then the motors to see how the robot behaves.

**Comment by jimingda** [comment]
Hi  @AntonioConsilvio 

Shall i disconnect the 2pin connector at the same time when i disconnect the 3pin connector？

**Comment by jimingda** [comment]
Hi @AntonioConsilvio 

What is the possible causes of the CPU power problem

**Comment by jimingda** [comment]
Hi @AntonioConsilvio,

I apologize for any inconvenience, but could you please spare a moment to look into this issue? I have been struggling with it for quite some time.

Thank you!

**Comment by AntonioConsilvio** [comment]
Hi @jimingda, sorry for the wait. I've been busy with some internal demonstrations over the last few days.
 
So, according to the latest information you provided, the problem seems to be with the motor power supply, which due to a short circuit, for example, could cause the robot to shut down.
We need to find out in which part of the robot this problem occurs by exclusion.
 
To do this, I would start with the power source, namely the `BDC` board. 
First, reconnect the previously disconnected head connectors. Then to reach the `BDC` board, you have to remove the backpack by unscrewing the screws and pulling it carefully:
 
![back1](https://github.com/user-attachments/assets/0bb6e147-d14e-4a17-a6db-c19248f9011a)

![back2](https://github.com/user-attachments/assets/25b286a2-7543-4801-816c-431954d8c1a9)

At this point, the board looks like this on one side of the robot:
 
![bdc1](https://github.com/user-attachments/assets/66644cfb-c5e4-4639-ac8b-782fdeab5b50)


Following the diagram, I recommend that you unscrew all the alimetations (j3 - j4 - j5) and do a power-up test to see how it behaves.

![image](https://github.com/user-attachments/assets/566409dd-5dfd-4a38-9dd5-d85a0521367c)


After that, if the buttons don't behave strangely, I suggest to reconnect everything step by step.

First the CPU (j5), and do a power-up test.

If all goes well, try connecting the motors (j4) and test.

And finally the body motors (j3).

When the problem reappears then the problem is in that part of the robot. 

Please, send us feedback and if you have any questions feel free to ask!

**Comment by AntonioConsilvio** [comment]
Hi @jimingda, you have to unscrew the eyebolts too:

![backpack](https://github.com/user-attachments/assets/12f207fe-0be6-4c4a-b4aa-05f544a06374)

**Comment by jimingda** [comment]
Thank you @AntonioConsilvio  for quick response.

I still can't remove the backpack after unscrew the eyebolts. Maybe there are other connections i didn't remove.
Shall i cut this on the bottom of the backpack?
![3742c21c5saaa0cc77a88dec5dbeac53](https://github.com/user-attachments/assets/b7205962-8b86-4c23-9fb9-c13f97596668)

**Comment by AntonioConsilvio** [comment]
Yes! Cut the cable tie

**Comment by jimingda** [comment]
Hi @AntonioConsilvio 

I cut that cable tie, but still  can't remove the backpack.

**Comment by AntonioConsilvio** [comment]
Hi @jimingda make sure you have removed all connections (such as power supply or Ethernet):

![IMG_20240722_170306](https://github.com/user-attachments/assets/17b01edf-ffab-48bc-8e77-a4809df357b5)


And try unscrewing these two screws (red in the picture below), then remove the dummy battery by pulling up on the lever circled in blue: 

![IMG_20240722_170259](https://github.com/user-attachments/assets/95b4d05c-8f6a-463e-8dd4-9ceaba7f21d3)


Then try removing the cover.

> [!Note]
> TIP: in the picture above, you may notice a green circle, it may help to loosen (not remove) that screw, and also the one next to it that holds the same electronic board, and carefully push the board against the mechanics. By doing so, the buttons will not be too much of a nuisance when removing the cover. It is not necessary, but useful.

**Comment by jimingda** [comment]
Thanks @AntonioConsilvio 

I manage to remove the backpack. Then do the test as your advice in the reverse sequence.

First, disconnect  j3 (which means j4 & j5 connected), turn on CPU and then turn on Motor, after 30 seconds, both shut down automatically. 

Then, disconnect j4 (which means only j5 connected, as the pic below), turn on CPU and then turn on Motor. It's normal now, CPU and Motor power didn't shut down. 

![10d22595ch98e0d0a4abd232f842ba18](https://github.com/user-attachments/assets/05a2d229-c57d-4e79-ab32-28a4a2649cef)

**Comment by AntonioConsilvio** [comment]
Hi @jimingda, great job! 

Then, let's exclude J3 from the possible cause.

Let's talk instead about j4, which seems to be the problem there. 

As you can see in the electrical diagram in this [comment](https://github.com/robotology/icub-tech-support/issues/1826#issuecomment-2233229182):

At PIN1 and 4 (J4_1 and J4_4) the 12V of the head boards are connected, while at PIN2 and 3 (J4_2 and J4_3), the 12V of the arms boards are connected.

Try keeping only one of the two connected (e.g. those of the arms) and start the robot and see how it behaves. And then only the head ones and see how it behaves. By doing this test we should identify on which power supply the problem is located.

Regarding this question:

> How can i take the BDC from the backboard, because there is limited space to put the power cable into connector j3 j4 j5.

The board screws are behind the board itself, internal, where the dummy battery lodges. If you remove the dummy battery and look inside, you should see the screws.

Please, send us feedback and if you have any questions feel free to ask!

**Comment by jimingda** [comment]
Thanks @AntonioConsilvio 

I connect J4_1 and J4_4 (now only J5 & J4_1 J4_4 connected), turn on CPU and then Motor, after about 60 seconds they shut down automatically.

**Comment by AntonioConsilvio** [comment]
@jimingda and with J4_2 and J4_3 instead J4_1 and J4_4 what happens?

**Comment by jimingda** [comment]
@AntonioConsilvio 

Since i haven't take the BDC from the backpack, the space is limited.
Can i distribute the Larm_GND & Rarm_GND in J4_3 and J4_4, and distribute the Larm_12V & Rarm_12V in J4_1 and J4_2,
or just follow the diagram put two cables in one hole?

**Comment by AntonioConsilvio** [comment]
Hi @jimingda, The idea is to keep as close to schematic as possible (also during debugging). 
However, if you have huge difficulties, you can do what you said:

> Can i distribute the Larm_GND & Rarm_GND in J4_3 and J4_4, and distribute the Larm_12V & Rarm_12V in J4_1 and J4_2,
> or just follow the diagram put two cables in one hole?

**Comment by jimingda** [comment]
@AntonioConsilvio 

I connected J4_2 and J4_3 (now only J5, J4_2, and J4_3 are connected), turned on the CPU and then the motor. After about 60 seconds, they shut down automatically too. Since I haven't installed the left arm, only the right arm is functioning now.

**Comment by AntonioConsilvio** [comment]
Hi @jimingda, unfortunately I will not be available for several days, when I return we will try to figure out how to proceed!

Here you can find the electronics diagram of the board:

- https://github.com/icub-tech-iit/electronics-boards-public/tree/master/power-management/backpack-bdc

**Comment by jimingda** [comment]
Thanks @AntonioConsilvio 

I disconnected the J4 cable and checked the voltages with a multimeter after powering on the CPU and Motor. The voltage was 12V. Then, I connected the head cable (+12V and GND), powered on the CPU, and then the Motor. The voltage remained at 12V, but it shut down automatically after 60 seconds, just like before.

**Comment by jimingda** [comment]
Hi @AntonioConsilvio 

It appears that the BDC board is functioning correctly and delivering the necessary voltage. Do you have any insights into what might be causing the issue?

**Comment by AntonioConsilvio** [comment]
Hi @jimingda! Have you tried to test whether there is continuity (and thus a short circuit) between 12V and GND, as suggested here:

> You could try disconnecting all the wires from J4, and using a multimeter to check if the +12V and GND are short circuited.

**Comment by jimingda** [comment]
Hi @AntonioConsilvio 

I disconnected all the wires on J4. Before powering up, I verified that there was no short circuit between +12V and GND.

Then, I powered the CPU button and tested the voltage between +12V and GND with a multimeter. I found that there was a short circuit on J4.

**Comment by jimingda** [comment]
Hi @AntonioConsilvio 

Where can i find the schematic diagram of BDC board, i check the docs and didn't find it.
https://github.com/icub-tech-iit/electronics-boards-public/tree/master/power-management/backpack-bdc/docs

Thanks in advance.

**Comment by AntonioConsilvio** [comment]
Hi! Sorry for the long wait, I am aware of your issue, but unfortunately we do not have the availability to provide the proper support at the moment. We will get back to you as soon as possible.

**Comment by jimingda** [comment]
Hi @AntonioConsilvio,

The issue seems to be resolved. The root cause was that the current limit on the power transformer was set to 1A, which was insufficient to power the motor, causing it to shut down automatically. After increasing the current limit to 10A, the problem no longer occurred.

I know the voltage is set to 40V, but what is the recommended current limit for iCub? I couldn’t find this information in the documentation.

Thanks for your attention!
