### ISSUE TITLE
Rigth thumb encoder not working 

### ISSUE THREAD

**Issue by CarlottaSartore** [robotology/icub-tech-support#1827]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

Rigth-Thumbb open close encoder stops at one value.  

### Detailed context

Even if the joint is moved, the  value for the joint stay still at one value

**Comment by AntonioConsilvio** [comment]
Hi @CarlottaSartore, the problem was due a connector quite detached from the MMA board (the board were all fingers sensors are connected):

![IMG_20240619_133538](https://github.com/robotology/icub-tech-support/assets/114915464/e1ee1628-3761-4b16-8917-50a544f9b2a7)

I restored the connection and it works properly now! Closing! 🚀
