### ISSUE TITLE
ergoCub 1.1 S/N:001 – Ubuntu Partition Not Starting On Robot Laptop

### ISSUE THREAD

**Issue by SimoneMic** [robotology/icub-tech-support#1852]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

As per title, the robot partition doesn't start and was giving these errors (seems a memory corruption):
![20240716_140727](https://github.com/user-attachments/assets/2458506c-ecab-4407-a5e0-19f021904bf9)

I have tried accessing the windows partition and that was working properly, but after that I wasn't able to access the dual boot option, and the laptop started directly to windows.
This is another error that shows at startup:
![20240716_141414](https://github.com/user-attachments/assets/8b4b9c37-2ff4-4cc7-b81a-fbbd77e7884c)

### Detailed context

The laptop has been used in the morning and nothing strange was reported, everything was running fine.

### How does it affect you?

The robot cannot be used.

**Comment by AntonioConsilvio** [comment]
Hi @SimoneMic, @davidelasagna has restored dual boot access and it is now possible to access ubuntu.

However ubuntu doesn't boot correctly because the laptop has full storage.

Again with @davidelasagna's help we investigated a bit and found that the folders taking up the most space are:

![IMG_20240716_162654](https://github.com/user-attachments/assets/6b0c344b-96b8-4f7f-8bf1-a33757e4accb)

Mostly because there are very heavy folders (tens of GB) on the desktop, probably related to data collection (or similar), or what appear to be repositories. 

> [!Important]
> I would ask you to remove anything from these folders that is not strictly necessary and takes up a lot of space.
> And I also ask you in future to be very careful when downloading or accumulating heavy files, because the robot is not usable due to the malfunction of the laptop.


cc @S-Dafarra @GiulioRomualdi

**Comment by AntonioConsilvio** [comment]
I see that the PC is now working properly, thanks for freeing up some disk space.

Closing!
