### ISSUE TITLE
ergoCub 1.0 S/N:000 – ETH broken on right arm

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-tech-support#1918]
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

The eth backbone in the robot seems interrupted somewhere and the robot does not work well. The communication to the robot gets interrupted constantly

### Detailed context

@AntonioConsilvio  noted that the ETH cable in the right forearm seems broken

**Comment by AntonioConsilvio** [comment]
Hi @S-Dafarra! The problem at the ETH was perhaps due to the damaged power cable of the MC4-PLUS c-shape EB22 board. Turning off temporarily could have caused the ETH communication to be interrupted. 

![IMG_20240927_110727](https://github.com/user-attachments/assets/8dc53d87-6c6d-431b-a392-060cc1932539)

I fixed the cable, let's wait the next few days to see how the robot behaves.

**Comment by AntonioConsilvio** [comment]
The problem has not reoccurred, closing! ✅
