### ISSUE TITLE
ergoCub 1.1 S/N:001 – FT of left foot front not working

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1943]
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The FT sensor mounted under the left foot front streams constant values.

![Image](https://github.com/user-attachments/assets/f0d96a23-727c-4aec-b17e-6c28b80a5662)

### Detailed context

![Image](https://github.com/user-attachments/assets/cb4b5b9b-ef8c-4917-8336-f51d54c21a4b)

cc @mebbaid @SimoneMic @DanielePucci @Fabrizio69 @Gandoo

**Comment by Gandoo** [comment]
ho aperto la scarpa SX per verificare ma al momento non ho trovato fili rotti e/o schiacciati

**Comment by Gandoo** [comment]
dopo una verifica con @isorrentino e @AntonioConsilvio risultano i canali del sensore ID.14 saturi, procedo con la sostituzione.
...e siamo a 150!!

**Comment by Gandoo** [comment]
ciao, disassembled the foot and sole, replaced the FT sensor FT sensor cod.12487.A6 SN133 instead of the SN097 cod.12487.A3 
@isorrentino Updated ID and calibrated, now it works

![Image](https://github.com/user-attachments/assets/43e98dcf-c71d-43cd-8aef-3345be7a40a3)

![Image](https://github.com/user-attachments/assets/56c110ed-cc74-4bc2-8ef8-1c632310566c)


cc @AntonioConsilvio @Fabrizio69 @DanielePucci

**Comment by Gandoo** [comment]
ticket material used  https://github.com/icub-tech-iit/tickets/issues/3742#issuecomment-2429058881

**Comment by Gandoo** [comment]
ciao @isorrentino and @AntonioConsilvio  I replaced the RJ45 connector, but the problem is on the FED card which has a broken network connector.
 You have to remove the back to replace the board

![Image](https://github.com/user-attachments/assets/0c61ab71-38dd-4696-a2be-3e6199415e14)

cc @S-Dafarra @Fabrizio69
