### ISSUE TITLE
Meta-issue to track robot-specific configuration problems in the neck calibration

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-tech-support#500]
See https://github.com/robotology/robots-configuration/issues/36 (filled in `robots-configuration` as suggested in https://github.com/robotology/robots-configuration/issues/17).

This is just a meta-issue to make sure that the iCub support team knows that a set of robots is affected by this issue (using the robot-specific GitHub labels).

**Comment by traversaro** [comment]
cc @davidetome @julijenv @gabrielenava

**Comment by davidetome** [comment]
it happens on CAN based robots, you have to play with

**Comment by valegagge** [comment]
All these robots have CAN heads, but in their calibration head files is configured ParametricCalibrationEth instead of ParametricCalibration.

The ParametricCalibration doesn't use calibrationZero and CalibrationDelta parameters, so the user need to modify Zero parameter in the motorcontrol file as @davidetome had already wrote.

So to fix this issue we should change the calibrator device type and remove those parameters in order to not bring the user on wrong way.

For the future, could we update ParametricCalibration device in order to manage  calibrationZero and CalibrationDelta?

I don't know if it is possible and how much effort is needed.
