### ISSUE TITLE
CAD support shoulder

### ISSUE THREAD

**Issue by amaroyo** [robotology/icub-tech-support#879]
Hi @julijenv, 
cc @reafrancesco 

I am adding this issue as a reminder to solve the problem we have with the shoulders and the cable that eventually falls into the separation of the joint. Have you managed to find the CAD so to get the dimension of the separation? 

Thanks, 
Alex.

![IMG-20191025-WA0005](https://user-images.githubusercontent.com/11769446/68019905-489fad80-fc9d-11e9-864a-9957869eef01.jpg)
![IMG-20191025-WA0006](https://user-images.githubusercontent.com/11769446/68019906-489fad80-fc9d-11e9-9916-a0e14383065f.jpg)

**Comment by julijenv** [comment]
Hi @amaroyo , I tried to revert CAD Design to before the old shoulder piece (the one still on your robot) to get the size of this spacer. I was not able to find out the old design. not anymore in repository svn (too old). WCS I will have to compare between both shoulder of yours and shrink down the left one if found different.

**Comment by julijenv** [comment]
Hi @amaroyo, it has been checked and the piece is exactely the same in between the new shoulder and the old one (yours) so I will check what is precisely the probelm with your shoulder next time I come.

**Comment by amaroyo** [comment]
@julijenv, perfect! thanks!

**Comment by julijenv** [comment]
if after a week or so of testing you see that everything is ok, please close the issue thx.
@amaroyo

**Comment by amaroyo** [comment]
@julijenv, the cable (nº8) of the right shoulder is back in the hole again (see image). With the current tempo of experiments, in less than a week will be broken. 

![IMG_20191116_155718_427](https://user-images.githubusercontent.com/11769446/68995071-09bb4b80-088a-11ea-9a38-0cde1d3c9b8c.jpg)

**Comment by julijenv** [comment]
it has been solved, the spacer in between the shoulder and the pulley was out of specifics (1.65 instead of 1.5mm), file it make the trick - it has been done on both arm.

|IITCODE | Alias| REv.|Qty| Type|DEscription|
| --- | --- | --- | --- | --- | --- |
|4765 | RC_IIT_019_G_008 | 2 | 2  | Assemblies | SHOULDER ROTATION CABLE 8|
|4762 | RC_IIT_019_G_005 | 1 | 2  | Assemblies | SHOULDER ELEVATION CABLE 5|
|1895 | RC_IIT_003_P_006_00 |   |  2 | Freeform custom plastic parts (3D printing, molding) | LEFT PULLEY-CRIMP COVER|
|1896 | RC_IIT_003_P_007_00 |   |  2 | Freeform custom plastic parts (3D printing, molding) | RIGHT PULLEY-CRIMP COVER|
