### ISSUE TITLE
Purple iCub idling wrists when turning on

### ISSUE THREAD

**Issue by marco-monforte** [robotology/icub-tech-support#890]
## Brief description of the request/failure
Hey guys,
after turning on the yarprobotinterface and the calibration procedure, both left and right wrist are disabled and fall down.
As you know, on December 9th we have the visit of the IIT Scientifical and Technical Committee. It would be nice to fix this small issue. Thanks!

## Accompanying material

![20191121_120056](https://user-images.githubusercontent.com/32684998/69334383-dd714780-0c5a-11ea-843f-fca64ffe8f4c.jpg)

**Comment by marco-monforte** [comment]
Ciao! Next week (no precise day) Giulia needs the robot to start some experiments. Could we fix the wrists when you have some time?

**Comment by violadelbono** [comment]
Hello @marco-monforte 

The problem was due to the parameter `startupPosThreshold` in the calibration files of the arms. The threshold of joints 5 and 6 was initially set too low and thus the robot could not hold its wrists in position after the initial calibration. 

We changed the threshold from 2 to 90, according to the configuration files of the previous robots.

**Comment by marco-monforte** [comment]
Thanks @violadelbono and @julijenv !

I think for the time being is the best we can have. In the future, we could investigate why the wrists cannot reach an accurate delta threshold during the calibration stage (probably because of some PWM issue?).
