### ISSUE TITLE
i2c-3 line malfunction for ZCB to ED-MTB connection

### ISSUE THREAD

**Issue by arrenglover** [robotology/icub-tech-support#897]
## Brief description of the request/failure

The i2c-3 line on the ZCB (event-driven board) is scrambled when the yarprobotinterface is running.

## Detailed context

The i2c-3 line on the ZCB is used to connect to the ED-MTB board for event-driven skin. Currently it is connected via a cable that runs down the left arm of the robot to the left hand of the robot. When the yarprobotinterface is off we can successfully connect to the ED-MTB board via i2c protocol. A stable address 1e is correctly shown when running
```
sudo i2cdetect -y 3
```
on the icub-zynq board.

When the yarprobotinterface is turn on (and the robot is actively controlled), instead we cannot connect to the ED-MTB board and the 1e address is no longer stable

This issue has occurred before, I think the solution was to correctly insulate the cable such that motor noise would not affect the signals on the i2c line. Perhaps the cable has worn, moved, or damaged. 

@dabbous94 can be contacted to help with finding the issue (i.e. running the `i2cdetect` command correctly)

@ChiaraBartolozzi may have other information about how we solved the problem before.

**Comment by emilianob80** [comment]
@dabbous94 please can you contact me so let's see the problem together. Thanks

cc: @ChiaraBartolozzi @arrenglover

**Comment by emilianob80** [comment]
The wiring diagram used for electrical wiring is as follows:

[ZCB wiring.pdf](https://github.com/robotology/icub-tech-support/files/3930793/ZCB.wiring.pdf)

The shield connection was not foreseen and therefore, if the problem is caused by motor disturbances, I believe it is necessary to provide a shield connected to the GND pin on the head side. @MrAndrea  what do you think?

I apologize for my English

**Comment by emilianob80** [comment]
A verification on the robot has already highlighted the shield connected to GND even if not requested as a diagram. At this point I will try to re-crimp all the wires and reduce the length of the cable since it is present on the torso of abundance

I apologize for my English

**Comment by arrenglover** [comment]
Grazie @emilianob80!

I don't know why the problem started again, and couldn't identify the cause myself. Thanks for looking into it.

**Comment by emilianob80** [comment]
@arrenglover I crimped all the wires again and tested the continuity. Everything seems OK. When you arrive if you call me we will do some tests together.
Thanks

**Comment by arrenglover** [comment]
@dabbous94 - are you here today? Can you check the skin if the skin is now working correctly?

**Comment by dabbous94** [comment]
> @dabbous94 - are you here today? Can you check the skin if the skin is now working correctly?

yes, @arrenglover, Emiliano is here and we are working on solving the issue.

**Comment by emilianob80** [comment]
@arrenglover The skin works correctly at first boot but, in case of reboot with engines running, reboot fails. We did some tests and came to the conclusion that the left shoulder is the cause of the problems. With the left shoulder disabled the skin starts regularly. This problem cannot be solved at this time due to time constraints. I can, for the sake of scrupulousness, put a ferrite on my hand to see if we are lucky and the noise is reduced. For the demo, in case of skin restart, do it with the left shoulder disabled.
cc: @ChiaraBartolozzi

**Comment by arrenglover** [comment]
Thanks very much. That sounds good. We can work around the problem for the demo next week now you found the exact problem.

@emilianob80 - can you please put the icub head cover on the robot as soon as you can, I have to make a video of the robot this afternoon.

**Comment by emilianob80** [comment]
> Thanks very much. That sounds good. We can work around the problem for the demo next week now you found the exact problem.
> 
> @emilianob80 - can you please put the icub head cover on the robot as soon as you can, I have to make a video of the robot this afternoon.

@arrenglover 
- head cover ok
- ferrite has no benefits

**Comment by arrenglover** [comment]
@emilianob80 @dabbous94 @ChiaraBartolozzi - we should probably come up with a permanent solution to this problem
