### ISSUE TITLE
Purple iCub proximal joint cables broken for both thumbs

### ISSUE THREAD

**Issue by marco-monforte** [robotology/icub-tech-support#907]
## Brief description of the request/failure
The proximal joint cable is broken for both thumbs on the purple iCub.
The right one broke before Christmas during control/grasping experiments for the ERC commission; the left one broke this morning, January 15th, during the initial calibration procedure.

## Accompanying material

![20200115_095834](https://user-images.githubusercontent.com/32684998/72420892-8b4b2f00-3790-11ea-8fbf-d6ff02818dae.jpg)
![20200115_095854](https://user-images.githubusercontent.com/32684998/72420893-8b4b2f00-3790-11ea-838e-ce29bea82eb7.jpg)

**Comment by julijenv** [comment]
Hi @marco-monforte ,
The left thumb has been restored.
It has been taken from the warehouse the following pieces to do so.
|IITCODE|Ver.|Qta |DEscription|
|--|--|--|--|
|1895||1m|carlstahl cable 0.63mm|
|2391||0.5m|carlstahl cable 0.45-0.61mm: coated|

The robot needs to be as well recalibrated, I started but I stop due to other people wanted to use it. l.rapetti and yeshavi

**Comment by violadelbono** [comment]
Ciao @marco-monforte ,

We repaired the proximal joint of the right thumb. The cable was taken from warehouse:
|IITCODE|Ver.|Qta |DEscription|
|--|--|--|--|
|1815||1m|carlstahl cable 0.63mm||

We also recalibrated the robot (in .local so data will need to be pushed)

**Comment by marco-monforte** [comment]
Thanks a lot, @violadelbono and @julijenv! I close the issue then.
