### ISSUE TITLE
Connection between the iCub and PSU

### ISSUE THREAD

**Issue by astar-wuy** [robotology/icub-tech-support#925]
There seems to be a missing component between the PC104 part of the connection and the PSU. Please kindly help. Thank you.

![missing component](https://user-images.githubusercontent.com/61413832/75148269-35c45380-573a-11ea-81fc-e674cc921b75.jpg)

**Comment by julijenv** [comment]
Hi @astar-wuy ,
Actually this hanging cable is a one pin of  a Schottky diode, I presume the other part of it is still attached to the back of the power supply. Buy a new one and resolder the pins  and you are done.
Here the diode information:

4438 | STPS15L25D | Diodes, zener, transzorbs, TVS | Diode schottky,   Vrrm: 25V, If: 15A, Ifms: 250A, THD, TO220
-- | --  | -- | --

Here 2 references

 for the diode you need to buy

St microelectronics | STPS15L25D | FARNELL ITALIA S.R.L. | 9803408
-- | -- | -- | --
  |   | RS COMPONENTS S.P.A. | 714-6885

Here a diagram on how to connect the diode

![Diode_Schottky](https://user-images.githubusercontent.com/7140395/75243867-fb56c700-57ca-11ea-9164-bbf32fdd3d83.PNG)


![image](https://user-images.githubusercontent.com/7140395/75243549-5e942980-57ca-11ea-86a0-03df16c701c3.png)

have a nice day.

**Comment by astar-wuy** [comment]
Hi  Julien,
  Thanks for the drawings. Attached are the done wiring. Please let us know if anything is done wrongly. Thanks.

Best wishes,
Yan

**Comment by astar-wuy** [comment]
![1](https://user-images.githubusercontent.com/61413832/75321316-72638c80-58ab-11ea-87ca-c34823726f5b.jpg)
![2](https://user-images.githubusercontent.com/61413832/75321330-798a9a80-58ab-11ea-87d5-a277ce15d4fe.png)

**Comment by julijenv** [comment]
Hi @astar-wuy ,
almost perfect! The only thing that was not written so that why I need to tell you about is:
You need to place a thermally conductive BUT electrically isolated tape in between the back of the diode and the power supply.
here the information at this regards:

 | RS COMPONENTS S.P.A. | 477-4856| Thermally conductive double sided adhesive tape Bond-Ply 100, 152,4x152,4mm, Th 0,127mm, T 30/120°C, 0,8W/m•K|Bergquist | BP105-0.005-00-00-125X1506 |
|-- | -- | -- | --| --|

Hope this will help
let me know

**Comment by astar-wuy** [comment]
Hi Julien,
  Thanks a lot! We have got the tape and the robot is now up and running. Thanks once again!

Best wishes,
Yan
