### ISSUE TITLE
AEA Encoder Invalid Data

### ISSUE THREAD

**Issue by Quiescitus** [robotology/icub-tech-support#928]
## Brief description of the request/failure
When booting up the iCub with `yarprobotinterface` an error is encountered on Board 10.0.1.5 with the magnetic sensor.

Here's the startup log:
[iCubSheffield01-logfile.txt](https://github.com/robotology/icub-tech-support/files/4250301/iCubSheffield01-logfile.txt)

**Comment by julijenv** [comment]
Could you open the yarpmotorgui and check which joint of the torse is not giving you back values.
look the encoder value for those 3 joints and move the robot a bit when meanwhile rotating the 3 axes holding the robot (move the robot yourself, that was my sense)
give me feedback (screenshot of the robotmotorgui encircling the joint with no encoder value changing).
thx in advance

**Comment by dcam0050** [comment]
The issue is with the torso_roll encoder which doesn't change no matter in which direction I move the iCub.

Occasionally during the startup process, the robot does a small jolt forward like it's about to get up but that's it.

Also depending on how much time I leave between switching motors on and running `yarpmotorgui` I get different combinations of limbs and / or head with hardware faults.

![motorgui](https://user-images.githubusercontent.com/4288535/75261068-71b2f380-57e2-11ea-8db2-6739a0da2527.jpg)

**Comment by julijenv** [comment]
Hi @dcam0050  and @Quiescitus ,
Could you please check the integrity of the cable at the level of the waist-belly.
![image](https://user-images.githubusercontent.com/7140395/75333282-25b98a80-5886-11ea-9355-7a5c87ec41bc.png)

I do believe that it got pinched - more probably - or follow the cable and see if one the wire got broken or uncrimped.
let me know

**Comment by Quiescitus** [comment]
Hi @julijenv,
We followed that cable and it seems there's a section which feels like it was pinched (on image 1).

![1](https://user-images.githubusercontent.com/18901548/75342746-ecd1e380-588e-11ea-849b-452e7faff431.jpg)
![2](https://user-images.githubusercontent.com/18901548/75342750-ef343d80-588e-11ea-85bc-ce77e11a311e.jpg)
![3](https://user-images.githubusercontent.com/18901548/75342755-f1969780-588e-11ea-91ef-31b296b36cb3.jpg)

Not 100% certain, as we couldn't test with an amperemeter since one of the ends is sealed.
Any suggestions?

**Comment by julijenv** [comment]
Hi @Quiescitus ,
this part looks pinched to me
![image](https://user-images.githubusercontent.com/7140395/75344582-36283000-589b-11ea-8486-94529ff350b2.png)
remove the connector from the board and make a continuity tet with the board at the level of the belly (remove the 2 lateral screws, BEFORE just make sure you note how the plate and subsequently the sensor are placed because or else you could have a 180 degrees changed later when you will remount the overall).
Let me know

**Comment by Quiescitus** [comment]
@julijenv, That's indeed the case...
The cables are damaged around that spot. Do we need to order a replacement?

**Comment by julijenv** [comment]
Hi @Quiescitus ,
I will discuss tomorrow about sending you a spare part of it BUT my fear is that I will send you something that needs to be accompanied by another board from issue #911. Unfortunately, it looks like the board as a problem but you didn't quite really answer to my last question on it.
I need to see the screenshot of FirmwareUpdater when you have swapped the 2 can line and see either the FT sensor show up or not?
Let me know

**Comment by violadelbono** [comment]
The following items have been taken from the warehouse:

| IIT CODE       | Rev      |  Quantity          | Description  |
| ------------- |:-------------:| -----:| -----:|
|  1810     | A |  1 | AEA-001 Electronic board, 12-bit digital absolute encoder with spi interface |
|  1310     |   | 0.3 m | Teflon insulated cable, 5 poles, AWG32, 250V, with black braid, tape and jacket  |

**Comment by Quiescitus** [comment]
Thanks, we'll update this once there's more info on the order

**Comment by violadelbono** [comment]
The details about the pieces serve as a record just for us.
You will have more info at the shipping phase.
