### ISSUE TITLE
iCubGenova04 left elbow cable broken

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#933]
## Brief description of the request/failure
Today during some robot-robot weight lifting collaboration the right elbow of `iCubGenova04` broke.

## Accompanying material
![IMG_20200229_195815](https://user-images.githubusercontent.com/35487806/75615763-a4454f00-5b48-11ea-8995-f210bda8411d.jpg)
Moment of the failure
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35487806/75615867-b4a9f980-5b49-11ea-9c12-2afbaacd8dd8.gif)

**Comment by violadelbono** [comment]
Hi @lrapetti,

The cable 9 of the elbow was replaced and the functioning of the robot was tested afterwards.
We also noticed a problem of the wrist sensor AEA 2S2, due to a wire disconnection. The wire was thus re-welded to the sensor board.

IITCODE | Ver. | Qta | DEscription
-- | -- | -- | --
4766 | 1 | 1 | ELBOW CABLE 9
