### ISSUE TITLE
Generic Minor Failures

### ISSUE THREAD

**Issue by dariopasquali** [robotology/icub-tech-support#938]
Ciao @julijenv ,
in the last weeks me and @reafrancesco tested our application on the new iCubGenova07.
I'm going to report a few issues that came out. Could you please help us with them?

### 1. The control of Joints 7 (r/l_hand_fingers) of both hands is reversed
The joints move from pos.10 (fingers fully opened) to pos. 60 (fingers fully closed).
In our old iCubGenova03 the control is just the opposite: from 0 (closed) to 60 (opened).

We assume this is not the default also because we had to modify the RedBall demo in order to make it work. it tries to move the Joints 7 to Position 0 and generates an HW_FAULT error.

### 2. Joints 15 (r/l_little_fingers) of both hands
* On the **right hand**, the distal sections of the two little fingers do not move. They hit the palm of the hand at position 240 moving just the proximal.

* On the **left** **hand**, the motor turns without moving the fingers for an instant. When they start moving, they reach a maximum position of 134 (in a range of 0-256).

### 3. Joint 8 (r_thumb_opposite) and Joint 10 (r_thumb_distal) of right hand

If I move the Joint 8 to its maximum position, it triggers a contraction of Joint 10 which reaches also its maximum. After that, I can still move back and forth the Joint 8, while I can't move the Joint 10..
However, they are not in HW_FAULT on yarpmotorgui and no errors on yarprobotinterface log.

If I restart the yarprobotinterface, during the calibration, the thumb comes back to its position and then moves after the index (instead of before) hitting the index finger.
After that, everything works fine.

### Scratches and aluminium dust
Last week cable 6  of right shoulder came out. We suppose due to a loose tensioning of the cable. 
We fixed it without any problem but we noticed the clip that holds the crimp of the cable was full of aluminium dust and there are scratches on the metal part against it (I attach pictures below).

Right now I tensioned all the cables, but maybe our supposition is wrong and there are other hidden issues.

### Scratches on the back cover, under power supply plug
The power supply plug-in in certain positions hits the back cover scratching it.

### Fingers' sheaths
We have a few broken sheaths, as far as I remember:
* Distal right thumb
* Proximal right index
* Distal left index

### Aluminium Dust on Right Shoulder Cable 6 clip
![WhatsApp Image 2020-05-18 at 12 02 12](https://user-images.githubusercontent.com/11158169/83023993-f43f8f00-a02d-11ea-95fb-8cad6a680b5b.jpeg)

### Scratches on the metal part of Right Shoulder
![WhatsApp Image 2020-05-18 at 12 02 12 (2)](https://user-images.githubusercontent.com/11158169/83024050-0d484000-a02e-11ea-90b1-4862753a8938.jpeg)

### Scratches on the back cover
![WhatsApp Image 2020-05-18 at 12 02 12 (1)](https://user-images.githubusercontent.com/11158169/83024087-1e914c80-a02e-11ea-9e99-86589f5d1645.jpeg)

---

When could you come to Erzelli to check them?

Thank you!
Dario

**Comment by violadelbono** [comment]
Hi guys, a recap of what we did on iCubGenova07:

JOINTS CONTROL:
- The control of the fingers abduction is correct on this robot (but reversed in iCubGenova03):
fingers closed = 60 deg
fingers open = 0 deg

- We noticed that the sheaths of the right ring&pinkie fingers were too short, thus excessively tensing the fingers and requiring an extra force from the motor. We replaced the sheaths and the respective cables, then re-calibrated the joints

- We re-calibrated the left ring&pinkie joint as well

- Joint 8 (r_thumb_opposite) and Joint 10 (r_thumb_distal) of right hand: the oscillation of the thumb was due to a wrong magnet rotation (!!!review)

HARDWARE:

- The crimp holding cable 6 of right shoulder was mounted upside down and thus scratching the pulley with its movement and not holding the cable properly. It is now mounted correctly

-  The 90 deg curvature of the power supply plug-in was filed in order not to hit and damage the back cover anymore
