### ISSUE TITLE
Right leg calibration failure

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/icub-tech-support#962]
## Brief description of the request/failure

During some tests today, @lrapetti and I noticed the right leg calibration failure on iCubGenova02

## Accompanying material

Terminal debug info

[right_leg_calibration_fail.txt](https://github.com/robotology/icub-tech-support/files/4926185/right_leg_calibration_fail.txt)

**Comment by lrapetti** [comment]
The failure happened also when running the robot with the configuration launch file in `devel`

**Comment by julijenv** [comment]
Hi @lrapetti , I just return from the purple place and check the problem, at the moment everything seems ok when just the yarprobotinterface is launched from robotSartup-eventdriven . Legs are stiff. To me it looks lie a config file error, could you double-check?

**Comment by Yeshasvitvs** [comment]
@lrapetti we double checked this morning, and launching yarprobotinterface from the devel branch (which takes `icub_all.xml`) is running correctly without any failure of calibration of the right leg. Yesterday when you switched the branch to devel branch, did you install the robots-coniguration before running yarprobotinterface ?

**Comment by lrapetti** [comment]
I was running the file directly from the folder inside `robotology-superbuild/robotology/robots-configuration` since I didn't want to touch the file inside the other `robots-configuration` folder that is located outside the `robtology-superbuild` (to which if I am not wrong the YARP_DATA_DIRS points directly, so there is no installation required)

 Anyway, yesterday I tried with `icub_wbd.xml` file, I am wondering if this can be the difference.

I can test again tomorrow to check if I experience the same behaviour.

**Comment by lrapetti** [comment]
I tested it again today a few times with `icub_wbd.xml` and it started correctly all the time, I don't know what was wrong the last time but I think we can close the issue. Thanks.
